// Code generated by ent, DO NOT EDIT.

package imageversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the imageversion type in the database.
	Label = "image_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldParentVersionID holds the string denoting the parent_version_id field in the database.
	FieldParentVersionID = "parent_version_id"
	// FieldSourceVersionID holds the string denoting the source_version_id field in the database.
	FieldSourceVersionID = "source_version_id"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldPrompt holds the string denoting the prompt field in the database.
	FieldPrompt = "prompt"
	// FieldRevisedPrompt holds the string denoting the revised_prompt field in the database.
	FieldRevisedPrompt = "revised_prompt"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldMimeType holds the string denoting the mime_type field in the database.
	FieldMimeType = "mime_type"
	// FieldFilePath holds the string denoting the file_path field in the database.
	FieldFilePath = "file_path"
	// FieldFileSizeBytes holds the string denoting the file_size_bytes field in the database.
	FieldFileSizeBytes = "file_size_bytes"
	// FieldSha256 holds the string denoting the sha256 field in the database.
	FieldSha256 = "sha256"
	// FieldWidth holds the string denoting the width field in the database.
	FieldWidth = "width"
	// FieldHeight holds the string denoting the height field in the database.
	FieldHeight = "height"
	// FieldMaskFilePath holds the string denoting the mask_file_path field in the database.
	FieldMaskFilePath = "mask_file_path"
	// FieldMaskMimeType holds the string denoting the mask_mime_type field in the database.
	FieldMaskMimeType = "mask_mime_type"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the imageversion in the database.
	Table = "image_versions"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "image_versions"
	// ProjectInverseTable is the table name for the ImageProject entity.
	// It exists in this package in order to avoid circular dependency with the "imageproject" package.
	ProjectInverseTable = "image_projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "image_versions"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for imageversion fields.
var Columns = []string{
	FieldID,
	FieldProjectID,
	FieldUserID,
	FieldParentVersionID,
	FieldSourceVersionID,
	FieldMode,
	FieldPrompt,
	FieldRevisedPrompt,
	FieldModel,
	FieldSize,
	FieldMimeType,
	FieldFilePath,
	FieldFileSizeBytes,
	FieldSha256,
	FieldWidth,
	FieldHeight,
	FieldMaskFilePath,
	FieldMaskMimeType,
	FieldAPIKeyID,
	FieldUsageLogID,
	FieldCreatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModeValidator is a validator for the "mode" field. It is called by the builders before save.
	ModeValidator func(string) error
	// DefaultPrompt holds the default value on creation for the "prompt" field.
	DefaultPrompt string
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultSize holds the default value on creation for the "size" field.
	DefaultSize string
	// SizeValidator is a validator for the "size" field. It is called by the builders before save.
	SizeValidator func(string) error
	// MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	MimeTypeValidator func(string) error
	// FilePathValidator is a validator for the "file_path" field. It is called by the builders before save.
	FilePathValidator func(string) error
	// DefaultFileSizeBytes holds the default value on creation for the "file_size_bytes" field.
	DefaultFileSizeBytes int64
	// DefaultSha256 holds the default value on creation for the "sha256" field.
	DefaultSha256 string
	// Sha256Validator is a validator for the "sha256" field. It is called by the builders before save.
	Sha256Validator func(string) error
	// DefaultWidth holds the default value on creation for the "width" field.
	DefaultWidth int
	// DefaultHeight holds the default value on creation for the "height" field.
	DefaultHeight int
	// MaskMimeTypeValidator is a validator for the "mask_mime_type" field. It is called by the builders before save.
	MaskMimeTypeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ImageVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByParentVersionID orders the results by the parent_version_id field.
func ByParentVersionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentVersionID, opts...).ToFunc()
}

// BySourceVersionID orders the results by the source_version_id field.
func BySourceVersionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceVersionID, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByPrompt orders the results by the prompt field.
func ByPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrompt, opts...).ToFunc()
}

// ByRevisedPrompt orders the results by the revised_prompt field.
func ByRevisedPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevisedPrompt, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByMimeType orders the results by the mime_type field.
func ByMimeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMimeType, opts...).ToFunc()
}

// ByFilePath orders the results by the file_path field.
func ByFilePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilePath, opts...).ToFunc()
}

// ByFileSizeBytes orders the results by the file_size_bytes field.
func ByFileSizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileSizeBytes, opts...).ToFunc()
}

// BySha256 orders the results by the sha256 field.
func BySha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSha256, opts...).ToFunc()
}

// ByWidth orders the results by the width field.
func ByWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWidth, opts...).ToFunc()
}

// ByHeight orders the results by the height field.
func ByHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeight, opts...).ToFunc()
}

// ByMaskFilePath orders the results by the mask_file_path field.
func ByMaskFilePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaskFilePath, opts...).ToFunc()
}

// ByMaskMimeType orders the results by the mask_mime_type field.
func ByMaskMimeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaskMimeType, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
