// Code generated by ent, DO NOT EDIT.

package imageversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldProjectID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldUserID, v))
}

// ParentVersionID applies equality check predicate on the "parent_version_id" field. It's identical to ParentVersionIDEQ.
func ParentVersionID(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldParentVersionID, v))
}

// SourceVersionID applies equality check predicate on the "source_version_id" field. It's identical to SourceVersionIDEQ.
func SourceVersionID(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldSourceVersionID, v))
}

// Mode applies equality check predicate on the "mode" field. It's identical to ModeEQ.
func Mode(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldMode, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldPrompt, v))
}

// RevisedPrompt applies equality check predicate on the "revised_prompt" field. It's identical to RevisedPromptEQ.
func RevisedPrompt(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldRevisedPrompt, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldModel, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldSize, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldMimeType, v))
}

// FilePath applies equality check predicate on the "file_path" field. It's identical to FilePathEQ.
func FilePath(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldFilePath, v))
}

// FileSizeBytes applies equality check predicate on the "file_size_bytes" field. It's identical to FileSizeBytesEQ.
func FileSizeBytes(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldFileSizeBytes, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldSha256, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldHeight, v))
}

// MaskFilePath applies equality check predicate on the "mask_file_path" field. It's identical to MaskFilePathEQ.
func MaskFilePath(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldMaskFilePath, v))
}

// MaskMimeType applies equality check predicate on the "mask_mime_type" field. It's identical to MaskMimeTypeEQ.
func MaskMimeType(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldMaskMimeType, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldAPIKeyID, v))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldUsageLogID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldDeletedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldProjectID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldUserID, vs...))
}

// ParentVersionIDEQ applies the EQ predicate on the "parent_version_id" field.
func ParentVersionIDEQ(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldParentVersionID, v))
}

// ParentVersionIDNEQ applies the NEQ predicate on the "parent_version_id" field.
func ParentVersionIDNEQ(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldParentVersionID, v))
}

// ParentVersionIDIn applies the In predicate on the "parent_version_id" field.
func ParentVersionIDIn(vs ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldParentVersionID, vs...))
}

// ParentVersionIDNotIn applies the NotIn predicate on the "parent_version_id" field.
func ParentVersionIDNotIn(vs ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldParentVersionID, vs...))
}

// ParentVersionIDGT applies the GT predicate on the "parent_version_id" field.
func ParentVersionIDGT(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldParentVersionID, v))
}

// ParentVersionIDGTE applies the GTE predicate on the "parent_version_id" field.
func ParentVersionIDGTE(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldParentVersionID, v))
}

// ParentVersionIDLT applies the LT predicate on the "parent_version_id" field.
func ParentVersionIDLT(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldParentVersionID, v))
}

// ParentVersionIDLTE applies the LTE predicate on the "parent_version_id" field.
func ParentVersionIDLTE(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldParentVersionID, v))
}

// ParentVersionIDIsNil applies the IsNil predicate on the "parent_version_id" field.
func ParentVersionIDIsNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIsNull(FieldParentVersionID))
}

// ParentVersionIDNotNil applies the NotNil predicate on the "parent_version_id" field.
func ParentVersionIDNotNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotNull(FieldParentVersionID))
}

// SourceVersionIDEQ applies the EQ predicate on the "source_version_id" field.
func SourceVersionIDEQ(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldSourceVersionID, v))
}

// SourceVersionIDNEQ applies the NEQ predicate on the "source_version_id" field.
func SourceVersionIDNEQ(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldSourceVersionID, v))
}

// SourceVersionIDIn applies the In predicate on the "source_version_id" field.
func SourceVersionIDIn(vs ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldSourceVersionID, vs...))
}

// SourceVersionIDNotIn applies the NotIn predicate on the "source_version_id" field.
func SourceVersionIDNotIn(vs ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldSourceVersionID, vs...))
}

// SourceVersionIDGT applies the GT predicate on the "source_version_id" field.
func SourceVersionIDGT(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldSourceVersionID, v))
}

// SourceVersionIDGTE applies the GTE predicate on the "source_version_id" field.
func SourceVersionIDGTE(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldSourceVersionID, v))
}

// SourceVersionIDLT applies the LT predicate on the "source_version_id" field.
func SourceVersionIDLT(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldSourceVersionID, v))
}

// SourceVersionIDLTE applies the LTE predicate on the "source_version_id" field.
func SourceVersionIDLTE(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldSourceVersionID, v))
}

// SourceVersionIDIsNil applies the IsNil predicate on the "source_version_id" field.
func SourceVersionIDIsNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIsNull(FieldSourceVersionID))
}

// SourceVersionIDNotNil applies the NotNil predicate on the "source_version_id" field.
func SourceVersionIDNotNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotNull(FieldSourceVersionID))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldMode, vs...))
}

// ModeGT applies the GT predicate on the "mode" field.
func ModeGT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldMode, v))
}

// ModeGTE applies the GTE predicate on the "mode" field.
func ModeGTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldMode, v))
}

// ModeLT applies the LT predicate on the "mode" field.
func ModeLT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldMode, v))
}

// ModeLTE applies the LTE predicate on the "mode" field.
func ModeLTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldMode, v))
}

// ModeContains applies the Contains predicate on the "mode" field.
func ModeContains(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContains(FieldMode, v))
}

// ModeHasPrefix applies the HasPrefix predicate on the "mode" field.
func ModeHasPrefix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasPrefix(FieldMode, v))
}

// ModeHasSuffix applies the HasSuffix predicate on the "mode" field.
func ModeHasSuffix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasSuffix(FieldMode, v))
}

// ModeEqualFold applies the EqualFold predicate on the "mode" field.
func ModeEqualFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEqualFold(FieldMode, v))
}

// ModeContainsFold applies the ContainsFold predicate on the "mode" field.
func ModeContainsFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContainsFold(FieldMode, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContainsFold(FieldPrompt, v))
}

// RevisedPromptEQ applies the EQ predicate on the "revised_prompt" field.
func RevisedPromptEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldRevisedPrompt, v))
}

// RevisedPromptNEQ applies the NEQ predicate on the "revised_prompt" field.
func RevisedPromptNEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldRevisedPrompt, v))
}

// RevisedPromptIn applies the In predicate on the "revised_prompt" field.
func RevisedPromptIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldRevisedPrompt, vs...))
}

// RevisedPromptNotIn applies the NotIn predicate on the "revised_prompt" field.
func RevisedPromptNotIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldRevisedPrompt, vs...))
}

// RevisedPromptGT applies the GT predicate on the "revised_prompt" field.
func RevisedPromptGT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldRevisedPrompt, v))
}

// RevisedPromptGTE applies the GTE predicate on the "revised_prompt" field.
func RevisedPromptGTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldRevisedPrompt, v))
}

// RevisedPromptLT applies the LT predicate on the "revised_prompt" field.
func RevisedPromptLT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldRevisedPrompt, v))
}

// RevisedPromptLTE applies the LTE predicate on the "revised_prompt" field.
func RevisedPromptLTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldRevisedPrompt, v))
}

// RevisedPromptContains applies the Contains predicate on the "revised_prompt" field.
func RevisedPromptContains(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContains(FieldRevisedPrompt, v))
}

// RevisedPromptHasPrefix applies the HasPrefix predicate on the "revised_prompt" field.
func RevisedPromptHasPrefix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasPrefix(FieldRevisedPrompt, v))
}

// RevisedPromptHasSuffix applies the HasSuffix predicate on the "revised_prompt" field.
func RevisedPromptHasSuffix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasSuffix(FieldRevisedPrompt, v))
}

// RevisedPromptIsNil applies the IsNil predicate on the "revised_prompt" field.
func RevisedPromptIsNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIsNull(FieldRevisedPrompt))
}

// RevisedPromptNotNil applies the NotNil predicate on the "revised_prompt" field.
func RevisedPromptNotNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotNull(FieldRevisedPrompt))
}

// RevisedPromptEqualFold applies the EqualFold predicate on the "revised_prompt" field.
func RevisedPromptEqualFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEqualFold(FieldRevisedPrompt, v))
}

// RevisedPromptContainsFold applies the ContainsFold predicate on the "revised_prompt" field.
func RevisedPromptContainsFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContainsFold(FieldRevisedPrompt, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContainsFold(FieldModel, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldSize, v))
}

// SizeContains applies the Contains predicate on the "size" field.
func SizeContains(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContains(FieldSize, v))
}

// SizeHasPrefix applies the HasPrefix predicate on the "size" field.
func SizeHasPrefix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasPrefix(FieldSize, v))
}

// SizeHasSuffix applies the HasSuffix predicate on the "size" field.
func SizeHasSuffix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasSuffix(FieldSize, v))
}

// SizeEqualFold applies the EqualFold predicate on the "size" field.
func SizeEqualFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEqualFold(FieldSize, v))
}

// SizeContainsFold applies the ContainsFold predicate on the "size" field.
func SizeContainsFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContainsFold(FieldSize, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContainsFold(FieldMimeType, v))
}

// FilePathEQ applies the EQ predicate on the "file_path" field.
func FilePathEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldFilePath, v))
}

// FilePathNEQ applies the NEQ predicate on the "file_path" field.
func FilePathNEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldFilePath, v))
}

// FilePathIn applies the In predicate on the "file_path" field.
func FilePathIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldFilePath, vs...))
}

// FilePathNotIn applies the NotIn predicate on the "file_path" field.
func FilePathNotIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldFilePath, vs...))
}

// FilePathGT applies the GT predicate on the "file_path" field.
func FilePathGT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldFilePath, v))
}

// FilePathGTE applies the GTE predicate on the "file_path" field.
func FilePathGTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldFilePath, v))
}

// FilePathLT applies the LT predicate on the "file_path" field.
func FilePathLT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldFilePath, v))
}

// FilePathLTE applies the LTE predicate on the "file_path" field.
func FilePathLTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldFilePath, v))
}

// FilePathContains applies the Contains predicate on the "file_path" field.
func FilePathContains(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContains(FieldFilePath, v))
}

// FilePathHasPrefix applies the HasPrefix predicate on the "file_path" field.
func FilePathHasPrefix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasPrefix(FieldFilePath, v))
}

// FilePathHasSuffix applies the HasSuffix predicate on the "file_path" field.
func FilePathHasSuffix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasSuffix(FieldFilePath, v))
}

// FilePathEqualFold applies the EqualFold predicate on the "file_path" field.
func FilePathEqualFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEqualFold(FieldFilePath, v))
}

// FilePathContainsFold applies the ContainsFold predicate on the "file_path" field.
func FilePathContainsFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContainsFold(FieldFilePath, v))
}

// FileSizeBytesEQ applies the EQ predicate on the "file_size_bytes" field.
func FileSizeBytesEQ(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldFileSizeBytes, v))
}

// FileSizeBytesNEQ applies the NEQ predicate on the "file_size_bytes" field.
func FileSizeBytesNEQ(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldFileSizeBytes, v))
}

// FileSizeBytesIn applies the In predicate on the "file_size_bytes" field.
func FileSizeBytesIn(vs ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldFileSizeBytes, vs...))
}

// FileSizeBytesNotIn applies the NotIn predicate on the "file_size_bytes" field.
func FileSizeBytesNotIn(vs ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldFileSizeBytes, vs...))
}

// FileSizeBytesGT applies the GT predicate on the "file_size_bytes" field.
func FileSizeBytesGT(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldFileSizeBytes, v))
}

// FileSizeBytesGTE applies the GTE predicate on the "file_size_bytes" field.
func FileSizeBytesGTE(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldFileSizeBytes, v))
}

// FileSizeBytesLT applies the LT predicate on the "file_size_bytes" field.
func FileSizeBytesLT(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldFileSizeBytes, v))
}

// FileSizeBytesLTE applies the LTE predicate on the "file_size_bytes" field.
func FileSizeBytesLTE(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldFileSizeBytes, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContainsFold(FieldSha256, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldWidth, v))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldHeight, v))
}

// MaskFilePathEQ applies the EQ predicate on the "mask_file_path" field.
func MaskFilePathEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldMaskFilePath, v))
}

// MaskFilePathNEQ applies the NEQ predicate on the "mask_file_path" field.
func MaskFilePathNEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldMaskFilePath, v))
}

// MaskFilePathIn applies the In predicate on the "mask_file_path" field.
func MaskFilePathIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldMaskFilePath, vs...))
}

// MaskFilePathNotIn applies the NotIn predicate on the "mask_file_path" field.
func MaskFilePathNotIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldMaskFilePath, vs...))
}

// MaskFilePathGT applies the GT predicate on the "mask_file_path" field.
func MaskFilePathGT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldMaskFilePath, v))
}

// MaskFilePathGTE applies the GTE predicate on the "mask_file_path" field.
func MaskFilePathGTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldMaskFilePath, v))
}

// MaskFilePathLT applies the LT predicate on the "mask_file_path" field.
func MaskFilePathLT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldMaskFilePath, v))
}

// MaskFilePathLTE applies the LTE predicate on the "mask_file_path" field.
func MaskFilePathLTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldMaskFilePath, v))
}

// MaskFilePathContains applies the Contains predicate on the "mask_file_path" field.
func MaskFilePathContains(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContains(FieldMaskFilePath, v))
}

// MaskFilePathHasPrefix applies the HasPrefix predicate on the "mask_file_path" field.
func MaskFilePathHasPrefix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasPrefix(FieldMaskFilePath, v))
}

// MaskFilePathHasSuffix applies the HasSuffix predicate on the "mask_file_path" field.
func MaskFilePathHasSuffix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasSuffix(FieldMaskFilePath, v))
}

// MaskFilePathIsNil applies the IsNil predicate on the "mask_file_path" field.
func MaskFilePathIsNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIsNull(FieldMaskFilePath))
}

// MaskFilePathNotNil applies the NotNil predicate on the "mask_file_path" field.
func MaskFilePathNotNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotNull(FieldMaskFilePath))
}

// MaskFilePathEqualFold applies the EqualFold predicate on the "mask_file_path" field.
func MaskFilePathEqualFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEqualFold(FieldMaskFilePath, v))
}

// MaskFilePathContainsFold applies the ContainsFold predicate on the "mask_file_path" field.
func MaskFilePathContainsFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContainsFold(FieldMaskFilePath, v))
}

// MaskMimeTypeEQ applies the EQ predicate on the "mask_mime_type" field.
func MaskMimeTypeEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldMaskMimeType, v))
}

// MaskMimeTypeNEQ applies the NEQ predicate on the "mask_mime_type" field.
func MaskMimeTypeNEQ(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldMaskMimeType, v))
}

// MaskMimeTypeIn applies the In predicate on the "mask_mime_type" field.
func MaskMimeTypeIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldMaskMimeType, vs...))
}

// MaskMimeTypeNotIn applies the NotIn predicate on the "mask_mime_type" field.
func MaskMimeTypeNotIn(vs ...string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldMaskMimeType, vs...))
}

// MaskMimeTypeGT applies the GT predicate on the "mask_mime_type" field.
func MaskMimeTypeGT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldMaskMimeType, v))
}

// MaskMimeTypeGTE applies the GTE predicate on the "mask_mime_type" field.
func MaskMimeTypeGTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldMaskMimeType, v))
}

// MaskMimeTypeLT applies the LT predicate on the "mask_mime_type" field.
func MaskMimeTypeLT(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldMaskMimeType, v))
}

// MaskMimeTypeLTE applies the LTE predicate on the "mask_mime_type" field.
func MaskMimeTypeLTE(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldMaskMimeType, v))
}

// MaskMimeTypeContains applies the Contains predicate on the "mask_mime_type" field.
func MaskMimeTypeContains(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContains(FieldMaskMimeType, v))
}

// MaskMimeTypeHasPrefix applies the HasPrefix predicate on the "mask_mime_type" field.
func MaskMimeTypeHasPrefix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasPrefix(FieldMaskMimeType, v))
}

// MaskMimeTypeHasSuffix applies the HasSuffix predicate on the "mask_mime_type" field.
func MaskMimeTypeHasSuffix(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldHasSuffix(FieldMaskMimeType, v))
}

// MaskMimeTypeIsNil applies the IsNil predicate on the "mask_mime_type" field.
func MaskMimeTypeIsNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIsNull(FieldMaskMimeType))
}

// MaskMimeTypeNotNil applies the NotNil predicate on the "mask_mime_type" field.
func MaskMimeTypeNotNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotNull(FieldMaskMimeType))
}

// MaskMimeTypeEqualFold applies the EqualFold predicate on the "mask_mime_type" field.
func MaskMimeTypeEqualFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEqualFold(FieldMaskMimeType, v))
}

// MaskMimeTypeContainsFold applies the ContainsFold predicate on the "mask_mime_type" field.
func MaskMimeTypeContainsFold(v string) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldContainsFold(FieldMaskMimeType, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotNull(FieldAPIKeyID))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// UsageLogIDGT applies the GT predicate on the "usage_log_id" field.
func UsageLogIDGT(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldUsageLogID, v))
}

// UsageLogIDGTE applies the GTE predicate on the "usage_log_id" field.
func UsageLogIDGTE(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldUsageLogID, v))
}

// UsageLogIDLT applies the LT predicate on the "usage_log_id" field.
func UsageLogIDLT(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldUsageLogID, v))
}

// UsageLogIDLTE applies the LTE predicate on the "usage_log_id" field.
func UsageLogIDLTE(v int64) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldUsageLogID, v))
}

// UsageLogIDIsNil applies the IsNil predicate on the "usage_log_id" field.
func UsageLogIDIsNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIsNull(FieldUsageLogID))
}

// UsageLogIDNotNil applies the NotNil predicate on the "usage_log_id" field.
func UsageLogIDNotNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotNull(FieldUsageLogID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ImageVersion {
	return predicate.ImageVersion(sql.FieldNotNull(FieldDeletedAt))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.ImageVersion {
	return predicate.ImageVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.ImageProject) predicate.ImageVersion {
	return predicate.ImageVersion(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ImageVersion {
	return predicate.ImageVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ImageVersion {
	return predicate.ImageVersion(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImageVersion) predicate.ImageVersion {
	return predicate.ImageVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImageVersion) predicate.ImageVersion {
	return predicate.ImageVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImageVersion) predicate.ImageVersion {
	return predicate.ImageVersion(sql.NotPredicates(p))
}
