// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imageproject"
	"github.com/Wei-Shaw/sub2api/ent/imageversion"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ImageProjectCreate is the builder for creating a ImageProject entity.
type ImageProjectCreate struct {
	config
	mutation *ImageProjectMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImageProjectCreate) SetCreatedAt(v time.Time) *ImageProjectCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ImageProjectCreate) SetNillableCreatedAt(v *time.Time) *ImageProjectCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ImageProjectCreate) SetUpdatedAt(v time.Time) *ImageProjectCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ImageProjectCreate) SetNillableUpdatedAt(v *time.Time) *ImageProjectCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ImageProjectCreate) SetDeletedAt(v time.Time) *ImageProjectCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ImageProjectCreate) SetNillableDeletedAt(v *time.Time) *ImageProjectCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ImageProjectCreate) SetUserID(v int64) *ImageProjectCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ImageProjectCreate) SetTitle(v string) *ImageProjectCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *ImageProjectCreate) SetNillableTitle(v *string) *ImageProjectCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetCoverVersionID sets the "cover_version_id" field.
func (_c *ImageProjectCreate) SetCoverVersionID(v int64) *ImageProjectCreate {
	_c.mutation.SetCoverVersionID(v)
	return _c
}

// SetNillableCoverVersionID sets the "cover_version_id" field if the given value is not nil.
func (_c *ImageProjectCreate) SetNillableCoverVersionID(v *int64) *ImageProjectCreate {
	if v != nil {
		_c.SetCoverVersionID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ImageProjectCreate) SetStatus(v string) *ImageProjectCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ImageProjectCreate) SetNillableStatus(v *string) *ImageProjectCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ImageProjectCreate) SetUser(v *User) *ImageProjectCreate {
	return _c.SetUserID(v.ID)
}

// AddVersionIDs adds the "versions" edge to the ImageVersion entity by IDs.
func (_c *ImageProjectCreate) AddVersionIDs(ids ...int64) *ImageProjectCreate {
	_c.mutation.AddVersionIDs(ids...)
	return _c
}

// AddVersions adds the "versions" edges to the ImageVersion entity.
func (_c *ImageProjectCreate) AddVersions(v ...*ImageVersion) *ImageProjectCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVersionIDs(ids...)
}

// Mutation returns the ImageProjectMutation object of the builder.
func (_c *ImageProjectCreate) Mutation() *ImageProjectMutation {
	return _c.mutation
}

// Save creates the ImageProject in the database.
func (_c *ImageProjectCreate) Save(ctx context.Context) (*ImageProject, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImageProjectCreate) SaveX(ctx context.Context) *ImageProject {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageProjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageProjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImageProjectCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if imageproject.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized imageproject.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := imageproject.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if imageproject.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized imageproject.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := imageproject.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := imageproject.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := imageproject.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImageProjectCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ImageProject.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ImageProject.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ImageProject.user_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ImageProject.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := imageproject.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ImageProject.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ImageProject.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := imageproject.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImageProject.status": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ImageProject.user"`)}
	}
	return nil
}

func (_c *ImageProjectCreate) sqlSave(ctx context.Context) (*ImageProject, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImageProjectCreate) createSpec() (*ImageProject, *sqlgraph.CreateSpec) {
	var (
		_node = &ImageProject{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imageproject.Table, sqlgraph.NewFieldSpec(imageproject.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imageproject.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(imageproject.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(imageproject.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(imageproject.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.CoverVersionID(); ok {
		_spec.SetField(imageproject.FieldCoverVersionID, field.TypeInt64, value)
		_node.CoverVersionID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(imageproject.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imageproject.UserTable,
			Columns: []string{imageproject.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imageproject.VersionsTable,
			Columns: []string{imageproject.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imageversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageProject.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageProjectUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageProjectCreate) OnConflict(opts ...sql.ConflictOption) *ImageProjectUpsertOne {
	_c.conflict = opts
	return &ImageProjectUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageProject.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageProjectCreate) OnConflictColumns(columns ...string) *ImageProjectUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageProjectUpsertOne{
		create: _c,
	}
}

type (
	// ImageProjectUpsertOne is the builder for "upsert"-ing
	//  one ImageProject node.
	ImageProjectUpsertOne struct {
		create *ImageProjectCreate
	}

	// ImageProjectUpsert is the "OnConflict" setter.
	ImageProjectUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageProjectUpsert) SetUpdatedAt(v time.Time) *ImageProjectUpsert {
	u.Set(imageproject.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageProjectUpsert) UpdateUpdatedAt() *ImageProjectUpsert {
	u.SetExcluded(imageproject.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ImageProjectUpsert) SetDeletedAt(v time.Time) *ImageProjectUpsert {
	u.Set(imageproject.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ImageProjectUpsert) UpdateDeletedAt() *ImageProjectUpsert {
	u.SetExcluded(imageproject.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ImageProjectUpsert) ClearDeletedAt() *ImageProjectUpsert {
	u.SetNull(imageproject.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ImageProjectUpsert) SetUserID(v int64) *ImageProjectUpsert {
	u.Set(imageproject.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageProjectUpsert) UpdateUserID() *ImageProjectUpsert {
	u.SetExcluded(imageproject.FieldUserID)
	return u
}

// SetTitle sets the "title" field.
func (u *ImageProjectUpsert) SetTitle(v string) *ImageProjectUpsert {
	u.Set(imageproject.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ImageProjectUpsert) UpdateTitle() *ImageProjectUpsert {
	u.SetExcluded(imageproject.FieldTitle)
	return u
}

// SetCoverVersionID sets the "cover_version_id" field.
func (u *ImageProjectUpsert) SetCoverVersionID(v int64) *ImageProjectUpsert {
	u.Set(imageproject.FieldCoverVersionID, v)
	return u
}

// UpdateCoverVersionID sets the "cover_version_id" field to the value that was provided on create.
func (u *ImageProjectUpsert) UpdateCoverVersionID() *ImageProjectUpsert {
	u.SetExcluded(imageproject.FieldCoverVersionID)
	return u
}

// AddCoverVersionID adds v to the "cover_version_id" field.
func (u *ImageProjectUpsert) AddCoverVersionID(v int64) *ImageProjectUpsert {
	u.Add(imageproject.FieldCoverVersionID, v)
	return u
}

// ClearCoverVersionID clears the value of the "cover_version_id" field.
func (u *ImageProjectUpsert) ClearCoverVersionID() *ImageProjectUpsert {
	u.SetNull(imageproject.FieldCoverVersionID)
	return u
}

// SetStatus sets the "status" field.
func (u *ImageProjectUpsert) SetStatus(v string) *ImageProjectUpsert {
	u.Set(imageproject.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImageProjectUpsert) UpdateStatus() *ImageProjectUpsert {
	u.SetExcluded(imageproject.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ImageProject.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageProjectUpsertOne) UpdateNewValues() *ImageProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imageproject.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageProject.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImageProjectUpsertOne) Ignore() *ImageProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageProjectUpsertOne) DoNothing() *ImageProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageProjectCreate.OnConflict
// documentation for more info.
func (u *ImageProjectUpsertOne) Update(set func(*ImageProjectUpsert)) *ImageProjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageProjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageProjectUpsertOne) SetUpdatedAt(v time.Time) *ImageProjectUpsertOne {
	return u.Update(func(s *ImageProjectUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageProjectUpsertOne) UpdateUpdatedAt() *ImageProjectUpsertOne {
	return u.Update(func(s *ImageProjectUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ImageProjectUpsertOne) SetDeletedAt(v time.Time) *ImageProjectUpsertOne {
	return u.Update(func(s *ImageProjectUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ImageProjectUpsertOne) UpdateDeletedAt() *ImageProjectUpsertOne {
	return u.Update(func(s *ImageProjectUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ImageProjectUpsertOne) ClearDeletedAt() *ImageProjectUpsertOne {
	return u.Update(func(s *ImageProjectUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ImageProjectUpsertOne) SetUserID(v int64) *ImageProjectUpsertOne {
	return u.Update(func(s *ImageProjectUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageProjectUpsertOne) UpdateUserID() *ImageProjectUpsertOne {
	return u.Update(func(s *ImageProjectUpsert) {
		s.UpdateUserID()
	})
}

// SetTitle sets the "title" field.
func (u *ImageProjectUpsertOne) SetTitle(v string) *ImageProjectUpsertOne {
	return u.Update(func(s *ImageProjectUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ImageProjectUpsertOne) UpdateTitle() *ImageProjectUpsertOne {
	return u.Update(func(s *ImageProjectUpsert) {
		s.UpdateTitle()
	})
}

// SetCoverVersionID sets the "cover_version_id" field.
func (u *ImageProjectUpsertOne) SetCoverVersionID(v int64) *ImageProjectUpsertOne {
	return u.Update(func(s *ImageProjectUpsert) {
		s.SetCoverVersionID(v)
	})
}

// AddCoverVersionID adds v to the "cover_version_id" field.
func (u *ImageProjectUpsertOne) AddCoverVersionID(v int64) *ImageProjectUpsertOne {
	return u.Update(func(s *ImageProjectUpsert) {
		s.AddCoverVersionID(v)
	})
}

// UpdateCoverVersionID sets the "cover_version_id" field to the value that was provided on create.
func (u *ImageProjectUpsertOne) UpdateCoverVersionID() *ImageProjectUpsertOne {
	return u.Update(func(s *ImageProjectUpsert) {
		s.UpdateCoverVersionID()
	})
}

// ClearCoverVersionID clears the value of the "cover_version_id" field.
func (u *ImageProjectUpsertOne) ClearCoverVersionID() *ImageProjectUpsertOne {
	return u.Update(func(s *ImageProjectUpsert) {
		s.ClearCoverVersionID()
	})
}

// SetStatus sets the "status" field.
func (u *ImageProjectUpsertOne) SetStatus(v string) *ImageProjectUpsertOne {
	return u.Update(func(s *ImageProjectUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImageProjectUpsertOne) UpdateStatus() *ImageProjectUpsertOne {
	return u.Update(func(s *ImageProjectUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *ImageProjectUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageProjectCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageProjectUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImageProjectUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImageProjectUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImageProjectCreateBulk is the builder for creating many ImageProject entities in bulk.
type ImageProjectCreateBulk struct {
	config
	err      error
	builders []*ImageProjectCreate
	conflict []sql.ConflictOption
}

// Save creates the ImageProject entities in the database.
func (_c *ImageProjectCreateBulk) Save(ctx context.Context) ([]*ImageProject, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImageProject, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageProjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImageProjectCreateBulk) SaveX(ctx context.Context) []*ImageProject {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageProjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageProjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageProject.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageProjectUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageProjectCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImageProjectUpsertBulk {
	_c.conflict = opts
	return &ImageProjectUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageProject.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageProjectCreateBulk) OnConflictColumns(columns ...string) *ImageProjectUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageProjectUpsertBulk{
		create: _c,
	}
}

// ImageProjectUpsertBulk is the builder for "upsert"-ing
// a bulk of ImageProject nodes.
type ImageProjectUpsertBulk struct {
	create *ImageProjectCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ImageProject.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageProjectUpsertBulk) UpdateNewValues() *ImageProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imageproject.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageProject.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImageProjectUpsertBulk) Ignore() *ImageProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageProjectUpsertBulk) DoNothing() *ImageProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageProjectCreateBulk.OnConflict
// documentation for more info.
func (u *ImageProjectUpsertBulk) Update(set func(*ImageProjectUpsert)) *ImageProjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageProjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageProjectUpsertBulk) SetUpdatedAt(v time.Time) *ImageProjectUpsertBulk {
	return u.Update(func(s *ImageProjectUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageProjectUpsertBulk) UpdateUpdatedAt() *ImageProjectUpsertBulk {
	return u.Update(func(s *ImageProjectUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ImageProjectUpsertBulk) SetDeletedAt(v time.Time) *ImageProjectUpsertBulk {
	return u.Update(func(s *ImageProjectUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ImageProjectUpsertBulk) UpdateDeletedAt() *ImageProjectUpsertBulk {
	return u.Update(func(s *ImageProjectUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ImageProjectUpsertBulk) ClearDeletedAt() *ImageProjectUpsertBulk {
	return u.Update(func(s *ImageProjectUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ImageProjectUpsertBulk) SetUserID(v int64) *ImageProjectUpsertBulk {
	return u.Update(func(s *ImageProjectUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageProjectUpsertBulk) UpdateUserID() *ImageProjectUpsertBulk {
	return u.Update(func(s *ImageProjectUpsert) {
		s.UpdateUserID()
	})
}

// SetTitle sets the "title" field.
func (u *ImageProjectUpsertBulk) SetTitle(v string) *ImageProjectUpsertBulk {
	return u.Update(func(s *ImageProjectUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ImageProjectUpsertBulk) UpdateTitle() *ImageProjectUpsertBulk {
	return u.Update(func(s *ImageProjectUpsert) {
		s.UpdateTitle()
	})
}

// SetCoverVersionID sets the "cover_version_id" field.
func (u *ImageProjectUpsertBulk) SetCoverVersionID(v int64) *ImageProjectUpsertBulk {
	return u.Update(func(s *ImageProjectUpsert) {
		s.SetCoverVersionID(v)
	})
}

// AddCoverVersionID adds v to the "cover_version_id" field.
func (u *ImageProjectUpsertBulk) AddCoverVersionID(v int64) *ImageProjectUpsertBulk {
	return u.Update(func(s *ImageProjectUpsert) {
		s.AddCoverVersionID(v)
	})
}

// UpdateCoverVersionID sets the "cover_version_id" field to the value that was provided on create.
func (u *ImageProjectUpsertBulk) UpdateCoverVersionID() *ImageProjectUpsertBulk {
	return u.Update(func(s *ImageProjectUpsert) {
		s.UpdateCoverVersionID()
	})
}

// ClearCoverVersionID clears the value of the "cover_version_id" field.
func (u *ImageProjectUpsertBulk) ClearCoverVersionID() *ImageProjectUpsertBulk {
	return u.Update(func(s *ImageProjectUpsert) {
		s.ClearCoverVersionID()
	})
}

// SetStatus sets the "status" field.
func (u *ImageProjectUpsertBulk) SetStatus(v string) *ImageProjectUpsertBulk {
	return u.Update(func(s *ImageProjectUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImageProjectUpsertBulk) UpdateStatus() *ImageProjectUpsertBulk {
	return u.Update(func(s *ImageProjectUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *ImageProjectUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImageProjectCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageProjectCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageProjectUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
