// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imageproject"
	"github.com/Wei-Shaw/sub2api/ent/imageversion"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ImageProjectUpdate is the builder for updating ImageProject entities.
type ImageProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ImageProjectMutation
}

// Where appends a list predicates to the ImageProjectUpdate builder.
func (_u *ImageProjectUpdate) Where(ps ...predicate.ImageProject) *ImageProjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageProjectUpdate) SetUpdatedAt(v time.Time) *ImageProjectUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ImageProjectUpdate) SetDeletedAt(v time.Time) *ImageProjectUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ImageProjectUpdate) SetNillableDeletedAt(v *time.Time) *ImageProjectUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ImageProjectUpdate) ClearDeletedAt() *ImageProjectUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ImageProjectUpdate) SetUserID(v int64) *ImageProjectUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ImageProjectUpdate) SetNillableUserID(v *int64) *ImageProjectUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ImageProjectUpdate) SetTitle(v string) *ImageProjectUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ImageProjectUpdate) SetNillableTitle(v *string) *ImageProjectUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCoverVersionID sets the "cover_version_id" field.
func (_u *ImageProjectUpdate) SetCoverVersionID(v int64) *ImageProjectUpdate {
	_u.mutation.ResetCoverVersionID()
	_u.mutation.SetCoverVersionID(v)
	return _u
}

// SetNillableCoverVersionID sets the "cover_version_id" field if the given value is not nil.
func (_u *ImageProjectUpdate) SetNillableCoverVersionID(v *int64) *ImageProjectUpdate {
	if v != nil {
		_u.SetCoverVersionID(*v)
	}
	return _u
}

// AddCoverVersionID adds value to the "cover_version_id" field.
func (_u *ImageProjectUpdate) AddCoverVersionID(v int64) *ImageProjectUpdate {
	_u.mutation.AddCoverVersionID(v)
	return _u
}

// ClearCoverVersionID clears the value of the "cover_version_id" field.
func (_u *ImageProjectUpdate) ClearCoverVersionID() *ImageProjectUpdate {
	_u.mutation.ClearCoverVersionID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImageProjectUpdate) SetStatus(v string) *ImageProjectUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImageProjectUpdate) SetNillableStatus(v *string) *ImageProjectUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ImageProjectUpdate) SetUser(v *User) *ImageProjectUpdate {
	return _u.SetUserID(v.ID)
}

// AddVersionIDs adds the "versions" edge to the ImageVersion entity by IDs.
func (_u *ImageProjectUpdate) AddVersionIDs(ids ...int64) *ImageProjectUpdate {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the ImageVersion entity.
func (_u *ImageProjectUpdate) AddVersions(v ...*ImageVersion) *ImageProjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// Mutation returns the ImageProjectMutation object of the builder.
func (_u *ImageProjectUpdate) Mutation() *ImageProjectMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ImageProjectUpdate) ClearUser() *ImageProjectUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearVersions clears all "versions" edges to the ImageVersion entity.
func (_u *ImageProjectUpdate) ClearVersions() *ImageProjectUpdate {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to ImageVersion entities by IDs.
func (_u *ImageProjectUpdate) RemoveVersionIDs(ids ...int64) *ImageProjectUpdate {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to ImageVersion entities.
func (_u *ImageProjectUpdate) RemoveVersions(v ...*ImageVersion) *ImageProjectUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageProjectUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageProjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageProjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageProjectUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if imageproject.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized imageproject.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := imageproject.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageProjectUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := imageproject.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ImageProject.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := imageproject.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImageProject.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageProject.user"`)
	}
	return nil
}

func (_u *ImageProjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imageproject.Table, imageproject.Columns, sqlgraph.NewFieldSpec(imageproject.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imageproject.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(imageproject.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(imageproject.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(imageproject.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoverVersionID(); ok {
		_spec.SetField(imageproject.FieldCoverVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCoverVersionID(); ok {
		_spec.AddField(imageproject.FieldCoverVersionID, field.TypeInt64, value)
	}
	if _u.mutation.CoverVersionIDCleared() {
		_spec.ClearField(imageproject.FieldCoverVersionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(imageproject.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imageproject.UserTable,
			Columns: []string{imageproject.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imageproject.UserTable,
			Columns: []string{imageproject.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imageproject.VersionsTable,
			Columns: []string{imageproject.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imageversion.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imageproject.VersionsTable,
			Columns: []string{imageproject.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imageversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imageproject.VersionsTable,
			Columns: []string{imageproject.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imageversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imageproject.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageProjectUpdateOne is the builder for updating a single ImageProject entity.
type ImageProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageProjectMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageProjectUpdateOne) SetUpdatedAt(v time.Time) *ImageProjectUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ImageProjectUpdateOne) SetDeletedAt(v time.Time) *ImageProjectUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ImageProjectUpdateOne) SetNillableDeletedAt(v *time.Time) *ImageProjectUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ImageProjectUpdateOne) ClearDeletedAt() *ImageProjectUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ImageProjectUpdateOne) SetUserID(v int64) *ImageProjectUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ImageProjectUpdateOne) SetNillableUserID(v *int64) *ImageProjectUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ImageProjectUpdateOne) SetTitle(v string) *ImageProjectUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ImageProjectUpdateOne) SetNillableTitle(v *string) *ImageProjectUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCoverVersionID sets the "cover_version_id" field.
func (_u *ImageProjectUpdateOne) SetCoverVersionID(v int64) *ImageProjectUpdateOne {
	_u.mutation.ResetCoverVersionID()
	_u.mutation.SetCoverVersionID(v)
	return _u
}

// SetNillableCoverVersionID sets the "cover_version_id" field if the given value is not nil.
func (_u *ImageProjectUpdateOne) SetNillableCoverVersionID(v *int64) *ImageProjectUpdateOne {
	if v != nil {
		_u.SetCoverVersionID(*v)
	}
	return _u
}

// AddCoverVersionID adds value to the "cover_version_id" field.
func (_u *ImageProjectUpdateOne) AddCoverVersionID(v int64) *ImageProjectUpdateOne {
	_u.mutation.AddCoverVersionID(v)
	return _u
}

// ClearCoverVersionID clears the value of the "cover_version_id" field.
func (_u *ImageProjectUpdateOne) ClearCoverVersionID() *ImageProjectUpdateOne {
	_u.mutation.ClearCoverVersionID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImageProjectUpdateOne) SetStatus(v string) *ImageProjectUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImageProjectUpdateOne) SetNillableStatus(v *string) *ImageProjectUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ImageProjectUpdateOne) SetUser(v *User) *ImageProjectUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddVersionIDs adds the "versions" edge to the ImageVersion entity by IDs.
func (_u *ImageProjectUpdateOne) AddVersionIDs(ids ...int64) *ImageProjectUpdateOne {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the ImageVersion entity.
func (_u *ImageProjectUpdateOne) AddVersions(v ...*ImageVersion) *ImageProjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// Mutation returns the ImageProjectMutation object of the builder.
func (_u *ImageProjectUpdateOne) Mutation() *ImageProjectMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ImageProjectUpdateOne) ClearUser() *ImageProjectUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearVersions clears all "versions" edges to the ImageVersion entity.
func (_u *ImageProjectUpdateOne) ClearVersions() *ImageProjectUpdateOne {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to ImageVersion entities by IDs.
func (_u *ImageProjectUpdateOne) RemoveVersionIDs(ids ...int64) *ImageProjectUpdateOne {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to ImageVersion entities.
func (_u *ImageProjectUpdateOne) RemoveVersions(v ...*ImageVersion) *ImageProjectUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// Where appends a list predicates to the ImageProjectUpdate builder.
func (_u *ImageProjectUpdateOne) Where(ps ...predicate.ImageProject) *ImageProjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageProjectUpdateOne) Select(field string, fields ...string) *ImageProjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImageProject entity.
func (_u *ImageProjectUpdateOne) Save(ctx context.Context) (*ImageProject, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageProjectUpdateOne) SaveX(ctx context.Context) *ImageProject {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageProjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageProjectUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if imageproject.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized imageproject.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := imageproject.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageProjectUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := imageproject.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ImageProject.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := imageproject.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ImageProject.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageProject.user"`)
	}
	return nil
}

func (_u *ImageProjectUpdateOne) sqlSave(ctx context.Context) (_node *ImageProject, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imageproject.Table, imageproject.Columns, sqlgraph.NewFieldSpec(imageproject.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImageProject.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imageproject.FieldID)
		for _, f := range fields {
			if !imageproject.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imageproject.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imageproject.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(imageproject.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(imageproject.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(imageproject.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.CoverVersionID(); ok {
		_spec.SetField(imageproject.FieldCoverVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCoverVersionID(); ok {
		_spec.AddField(imageproject.FieldCoverVersionID, field.TypeInt64, value)
	}
	if _u.mutation.CoverVersionIDCleared() {
		_spec.ClearField(imageproject.FieldCoverVersionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(imageproject.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imageproject.UserTable,
			Columns: []string{imageproject.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imageproject.UserTable,
			Columns: []string{imageproject.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imageproject.VersionsTable,
			Columns: []string{imageproject.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imageversion.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imageproject.VersionsTable,
			Columns: []string{imageproject.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imageversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imageproject.VersionsTable,
			Columns: []string{imageproject.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imageversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ImageProject{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imageproject.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
