// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imageproject"
	"github.com/Wei-Shaw/sub2api/ent/imageversion"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ImageVersionCreate is the builder for creating a ImageVersion entity.
type ImageVersionCreate struct {
	config
	mutation *ImageVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProjectID sets the "project_id" field.
func (_c *ImageVersionCreate) SetProjectID(v int64) *ImageVersionCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ImageVersionCreate) SetUserID(v int64) *ImageVersionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetParentVersionID sets the "parent_version_id" field.
func (_c *ImageVersionCreate) SetParentVersionID(v int64) *ImageVersionCreate {
	_c.mutation.SetParentVersionID(v)
	return _c
}

// SetNillableParentVersionID sets the "parent_version_id" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillableParentVersionID(v *int64) *ImageVersionCreate {
	if v != nil {
		_c.SetParentVersionID(*v)
	}
	return _c
}

// SetSourceVersionID sets the "source_version_id" field.
func (_c *ImageVersionCreate) SetSourceVersionID(v int64) *ImageVersionCreate {
	_c.mutation.SetSourceVersionID(v)
	return _c
}

// SetNillableSourceVersionID sets the "source_version_id" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillableSourceVersionID(v *int64) *ImageVersionCreate {
	if v != nil {
		_c.SetSourceVersionID(*v)
	}
	return _c
}

// SetMode sets the "mode" field.
func (_c *ImageVersionCreate) SetMode(v string) *ImageVersionCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetPrompt sets the "prompt" field.
func (_c *ImageVersionCreate) SetPrompt(v string) *ImageVersionCreate {
	_c.mutation.SetPrompt(v)
	return _c
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillablePrompt(v *string) *ImageVersionCreate {
	if v != nil {
		_c.SetPrompt(*v)
	}
	return _c
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (_c *ImageVersionCreate) SetRevisedPrompt(v string) *ImageVersionCreate {
	_c.mutation.SetRevisedPrompt(v)
	return _c
}

// SetNillableRevisedPrompt sets the "revised_prompt" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillableRevisedPrompt(v *string) *ImageVersionCreate {
	if v != nil {
		_c.SetRevisedPrompt(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *ImageVersionCreate) SetModel(v string) *ImageVersionCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillableModel(v *string) *ImageVersionCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *ImageVersionCreate) SetSize(v string) *ImageVersionCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillableSize(v *string) *ImageVersionCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *ImageVersionCreate) SetMimeType(v string) *ImageVersionCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetFilePath sets the "file_path" field.
func (_c *ImageVersionCreate) SetFilePath(v string) *ImageVersionCreate {
	_c.mutation.SetFilePath(v)
	return _c
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (_c *ImageVersionCreate) SetFileSizeBytes(v int64) *ImageVersionCreate {
	_c.mutation.SetFileSizeBytes(v)
	return _c
}

// SetNillableFileSizeBytes sets the "file_size_bytes" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillableFileSizeBytes(v *int64) *ImageVersionCreate {
	if v != nil {
		_c.SetFileSizeBytes(*v)
	}
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *ImageVersionCreate) SetSha256(v string) *ImageVersionCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillableSha256(v *string) *ImageVersionCreate {
	if v != nil {
		_c.SetSha256(*v)
	}
	return _c
}

// SetWidth sets the "width" field.
func (_c *ImageVersionCreate) SetWidth(v int) *ImageVersionCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillableWidth(v *int) *ImageVersionCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *ImageVersionCreate) SetHeight(v int) *ImageVersionCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillableHeight(v *int) *ImageVersionCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetMaskFilePath sets the "mask_file_path" field.
func (_c *ImageVersionCreate) SetMaskFilePath(v string) *ImageVersionCreate {
	_c.mutation.SetMaskFilePath(v)
	return _c
}

// SetNillableMaskFilePath sets the "mask_file_path" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillableMaskFilePath(v *string) *ImageVersionCreate {
	if v != nil {
		_c.SetMaskFilePath(*v)
	}
	return _c
}

// SetMaskMimeType sets the "mask_mime_type" field.
func (_c *ImageVersionCreate) SetMaskMimeType(v string) *ImageVersionCreate {
	_c.mutation.SetMaskMimeType(v)
	return _c
}

// SetNillableMaskMimeType sets the "mask_mime_type" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillableMaskMimeType(v *string) *ImageVersionCreate {
	if v != nil {
		_c.SetMaskMimeType(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *ImageVersionCreate) SetAPIKeyID(v int64) *ImageVersionCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillableAPIKeyID(v *int64) *ImageVersionCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *ImageVersionCreate) SetUsageLogID(v int64) *ImageVersionCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillableUsageLogID(v *int64) *ImageVersionCreate {
	if v != nil {
		_c.SetUsageLogID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImageVersionCreate) SetCreatedAt(v time.Time) *ImageVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillableCreatedAt(v *time.Time) *ImageVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ImageVersionCreate) SetDeletedAt(v time.Time) *ImageVersionCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ImageVersionCreate) SetNillableDeletedAt(v *time.Time) *ImageVersionCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the ImageProject entity.
func (_c *ImageVersionCreate) SetProject(v *ImageProject) *ImageVersionCreate {
	return _c.SetProjectID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *ImageVersionCreate) SetUser(v *User) *ImageVersionCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ImageVersionMutation object of the builder.
func (_c *ImageVersionCreate) Mutation() *ImageVersionMutation {
	return _c.mutation
}

// Save creates the ImageVersion in the database.
func (_c *ImageVersionCreate) Save(ctx context.Context) (*ImageVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImageVersionCreate) SaveX(ctx context.Context) *ImageVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImageVersionCreate) defaults() {
	if _, ok := _c.mutation.Prompt(); !ok {
		v := imageversion.DefaultPrompt
		_c.mutation.SetPrompt(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := imageversion.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.Size(); !ok {
		v := imageversion.DefaultSize
		_c.mutation.SetSize(v)
	}
	if _, ok := _c.mutation.FileSizeBytes(); !ok {
		v := imageversion.DefaultFileSizeBytes
		_c.mutation.SetFileSizeBytes(v)
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		v := imageversion.DefaultSha256
		_c.mutation.SetSha256(v)
	}
	if _, ok := _c.mutation.Width(); !ok {
		v := imageversion.DefaultWidth
		_c.mutation.SetWidth(v)
	}
	if _, ok := _c.mutation.Height(); !ok {
		v := imageversion.DefaultHeight
		_c.mutation.SetHeight(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := imageversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImageVersionCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "ImageVersion.project_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ImageVersion.user_id"`)}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "ImageVersion.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := imageversion.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Prompt(); !ok {
		return &ValidationError{Name: "prompt", err: errors.New(`ent: missing required field "ImageVersion.prompt"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "ImageVersion.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := imageversion.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "ImageVersion.size"`)}
	}
	if v, ok := _c.mutation.Size(); ok {
		if err := imageversion.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "ImageVersion.mime_type"`)}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := imageversion.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FilePath(); !ok {
		return &ValidationError{Name: "file_path", err: errors.New(`ent: missing required field "ImageVersion.file_path"`)}
	}
	if v, ok := _c.mutation.FilePath(); ok {
		if err := imageversion.FilePathValidator(v); err != nil {
			return &ValidationError{Name: "file_path", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.file_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileSizeBytes(); !ok {
		return &ValidationError{Name: "file_size_bytes", err: errors.New(`ent: missing required field "ImageVersion.file_size_bytes"`)}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "ImageVersion.sha256"`)}
	}
	if v, ok := _c.mutation.Sha256(); ok {
		if err := imageversion.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`ent: missing required field "ImageVersion.width"`)}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "ImageVersion.height"`)}
	}
	if v, ok := _c.mutation.MaskMimeType(); ok {
		if err := imageversion.MaskMimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mask_mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.mask_mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ImageVersion.created_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "ImageVersion.project"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ImageVersion.user"`)}
	}
	return nil
}

func (_c *ImageVersionCreate) sqlSave(ctx context.Context) (*ImageVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImageVersionCreate) createSpec() (*ImageVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &ImageVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imageversion.Table, sqlgraph.NewFieldSpec(imageversion.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ParentVersionID(); ok {
		_spec.SetField(imageversion.FieldParentVersionID, field.TypeInt64, value)
		_node.ParentVersionID = &value
	}
	if value, ok := _c.mutation.SourceVersionID(); ok {
		_spec.SetField(imageversion.FieldSourceVersionID, field.TypeInt64, value)
		_node.SourceVersionID = &value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(imageversion.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.Prompt(); ok {
		_spec.SetField(imageversion.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := _c.mutation.RevisedPrompt(); ok {
		_spec.SetField(imageversion.FieldRevisedPrompt, field.TypeString, value)
		_node.RevisedPrompt = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(imageversion.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(imageversion.FieldSize, field.TypeString, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(imageversion.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.FilePath(); ok {
		_spec.SetField(imageversion.FieldFilePath, field.TypeString, value)
		_node.FilePath = value
	}
	if value, ok := _c.mutation.FileSizeBytes(); ok {
		_spec.SetField(imageversion.FieldFileSizeBytes, field.TypeInt64, value)
		_node.FileSizeBytes = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(imageversion.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(imageversion.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(imageversion.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.MaskFilePath(); ok {
		_spec.SetField(imageversion.FieldMaskFilePath, field.TypeString, value)
		_node.MaskFilePath = &value
	}
	if value, ok := _c.mutation.MaskMimeType(); ok {
		_spec.SetField(imageversion.FieldMaskMimeType, field.TypeString, value)
		_node.MaskMimeType = &value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(imageversion.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.UsageLogID(); ok {
		_spec.SetField(imageversion.FieldUsageLogID, field.TypeInt64, value)
		_node.UsageLogID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imageversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(imageversion.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imageversion.ProjectTable,
			Columns: []string{imageversion.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imageproject.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imageversion.UserTable,
			Columns: []string{imageversion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageVersion.Create().
//		SetProjectID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageVersionUpsert) {
//			SetProjectID(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageVersionCreate) OnConflict(opts ...sql.ConflictOption) *ImageVersionUpsertOne {
	_c.conflict = opts
	return &ImageVersionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageVersionCreate) OnConflictColumns(columns ...string) *ImageVersionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageVersionUpsertOne{
		create: _c,
	}
}

type (
	// ImageVersionUpsertOne is the builder for "upsert"-ing
	//  one ImageVersion node.
	ImageVersionUpsertOne struct {
		create *ImageVersionCreate
	}

	// ImageVersionUpsert is the "OnConflict" setter.
	ImageVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetProjectID sets the "project_id" field.
func (u *ImageVersionUpsert) SetProjectID(v int64) *ImageVersionUpsert {
	u.Set(imageversion.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateProjectID() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldProjectID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ImageVersionUpsert) SetUserID(v int64) *ImageVersionUpsert {
	u.Set(imageversion.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateUserID() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldUserID)
	return u
}

// SetParentVersionID sets the "parent_version_id" field.
func (u *ImageVersionUpsert) SetParentVersionID(v int64) *ImageVersionUpsert {
	u.Set(imageversion.FieldParentVersionID, v)
	return u
}

// UpdateParentVersionID sets the "parent_version_id" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateParentVersionID() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldParentVersionID)
	return u
}

// AddParentVersionID adds v to the "parent_version_id" field.
func (u *ImageVersionUpsert) AddParentVersionID(v int64) *ImageVersionUpsert {
	u.Add(imageversion.FieldParentVersionID, v)
	return u
}

// ClearParentVersionID clears the value of the "parent_version_id" field.
func (u *ImageVersionUpsert) ClearParentVersionID() *ImageVersionUpsert {
	u.SetNull(imageversion.FieldParentVersionID)
	return u
}

// SetSourceVersionID sets the "source_version_id" field.
func (u *ImageVersionUpsert) SetSourceVersionID(v int64) *ImageVersionUpsert {
	u.Set(imageversion.FieldSourceVersionID, v)
	return u
}

// UpdateSourceVersionID sets the "source_version_id" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateSourceVersionID() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldSourceVersionID)
	return u
}

// AddSourceVersionID adds v to the "source_version_id" field.
func (u *ImageVersionUpsert) AddSourceVersionID(v int64) *ImageVersionUpsert {
	u.Add(imageversion.FieldSourceVersionID, v)
	return u
}

// ClearSourceVersionID clears the value of the "source_version_id" field.
func (u *ImageVersionUpsert) ClearSourceVersionID() *ImageVersionUpsert {
	u.SetNull(imageversion.FieldSourceVersionID)
	return u
}

// SetMode sets the "mode" field.
func (u *ImageVersionUpsert) SetMode(v string) *ImageVersionUpsert {
	u.Set(imageversion.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateMode() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldMode)
	return u
}

// SetPrompt sets the "prompt" field.
func (u *ImageVersionUpsert) SetPrompt(v string) *ImageVersionUpsert {
	u.Set(imageversion.FieldPrompt, v)
	return u
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdatePrompt() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldPrompt)
	return u
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (u *ImageVersionUpsert) SetRevisedPrompt(v string) *ImageVersionUpsert {
	u.Set(imageversion.FieldRevisedPrompt, v)
	return u
}

// UpdateRevisedPrompt sets the "revised_prompt" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateRevisedPrompt() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldRevisedPrompt)
	return u
}

// ClearRevisedPrompt clears the value of the "revised_prompt" field.
func (u *ImageVersionUpsert) ClearRevisedPrompt() *ImageVersionUpsert {
	u.SetNull(imageversion.FieldRevisedPrompt)
	return u
}

// SetModel sets the "model" field.
func (u *ImageVersionUpsert) SetModel(v string) *ImageVersionUpsert {
	u.Set(imageversion.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateModel() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldModel)
	return u
}

// SetSize sets the "size" field.
func (u *ImageVersionUpsert) SetSize(v string) *ImageVersionUpsert {
	u.Set(imageversion.FieldSize, v)
	return u
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateSize() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldSize)
	return u
}

// SetMimeType sets the "mime_type" field.
func (u *ImageVersionUpsert) SetMimeType(v string) *ImageVersionUpsert {
	u.Set(imageversion.FieldMimeType, v)
	return u
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateMimeType() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldMimeType)
	return u
}

// SetFilePath sets the "file_path" field.
func (u *ImageVersionUpsert) SetFilePath(v string) *ImageVersionUpsert {
	u.Set(imageversion.FieldFilePath, v)
	return u
}

// UpdateFilePath sets the "file_path" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateFilePath() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldFilePath)
	return u
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (u *ImageVersionUpsert) SetFileSizeBytes(v int64) *ImageVersionUpsert {
	u.Set(imageversion.FieldFileSizeBytes, v)
	return u
}

// UpdateFileSizeBytes sets the "file_size_bytes" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateFileSizeBytes() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldFileSizeBytes)
	return u
}

// AddFileSizeBytes adds v to the "file_size_bytes" field.
func (u *ImageVersionUpsert) AddFileSizeBytes(v int64) *ImageVersionUpsert {
	u.Add(imageversion.FieldFileSizeBytes, v)
	return u
}

// SetSha256 sets the "sha256" field.
func (u *ImageVersionUpsert) SetSha256(v string) *ImageVersionUpsert {
	u.Set(imageversion.FieldSha256, v)
	return u
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateSha256() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldSha256)
	return u
}

// SetWidth sets the "width" field.
func (u *ImageVersionUpsert) SetWidth(v int) *ImageVersionUpsert {
	u.Set(imageversion.FieldWidth, v)
	return u
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateWidth() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldWidth)
	return u
}

// AddWidth adds v to the "width" field.
func (u *ImageVersionUpsert) AddWidth(v int) *ImageVersionUpsert {
	u.Add(imageversion.FieldWidth, v)
	return u
}

// SetHeight sets the "height" field.
func (u *ImageVersionUpsert) SetHeight(v int) *ImageVersionUpsert {
	u.Set(imageversion.FieldHeight, v)
	return u
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateHeight() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldHeight)
	return u
}

// AddHeight adds v to the "height" field.
func (u *ImageVersionUpsert) AddHeight(v int) *ImageVersionUpsert {
	u.Add(imageversion.FieldHeight, v)
	return u
}

// SetMaskFilePath sets the "mask_file_path" field.
func (u *ImageVersionUpsert) SetMaskFilePath(v string) *ImageVersionUpsert {
	u.Set(imageversion.FieldMaskFilePath, v)
	return u
}

// UpdateMaskFilePath sets the "mask_file_path" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateMaskFilePath() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldMaskFilePath)
	return u
}

// ClearMaskFilePath clears the value of the "mask_file_path" field.
func (u *ImageVersionUpsert) ClearMaskFilePath() *ImageVersionUpsert {
	u.SetNull(imageversion.FieldMaskFilePath)
	return u
}

// SetMaskMimeType sets the "mask_mime_type" field.
func (u *ImageVersionUpsert) SetMaskMimeType(v string) *ImageVersionUpsert {
	u.Set(imageversion.FieldMaskMimeType, v)
	return u
}

// UpdateMaskMimeType sets the "mask_mime_type" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateMaskMimeType() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldMaskMimeType)
	return u
}

// ClearMaskMimeType clears the value of the "mask_mime_type" field.
func (u *ImageVersionUpsert) ClearMaskMimeType() *ImageVersionUpsert {
	u.SetNull(imageversion.FieldMaskMimeType)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ImageVersionUpsert) SetAPIKeyID(v int64) *ImageVersionUpsert {
	u.Set(imageversion.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateAPIKeyID() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *ImageVersionUpsert) AddAPIKeyID(v int64) *ImageVersionUpsert {
	u.Add(imageversion.FieldAPIKeyID, v)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *ImageVersionUpsert) ClearAPIKeyID() *ImageVersionUpsert {
	u.SetNull(imageversion.FieldAPIKeyID)
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *ImageVersionUpsert) SetUsageLogID(v int64) *ImageVersionUpsert {
	u.Set(imageversion.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateUsageLogID() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldUsageLogID)
	return u
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *ImageVersionUpsert) AddUsageLogID(v int64) *ImageVersionUpsert {
	u.Add(imageversion.FieldUsageLogID, v)
	return u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *ImageVersionUpsert) ClearUsageLogID() *ImageVersionUpsert {
	u.SetNull(imageversion.FieldUsageLogID)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ImageVersionUpsert) SetDeletedAt(v time.Time) *ImageVersionUpsert {
	u.Set(imageversion.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ImageVersionUpsert) UpdateDeletedAt() *ImageVersionUpsert {
	u.SetExcluded(imageversion.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ImageVersionUpsert) ClearDeletedAt() *ImageVersionUpsert {
	u.SetNull(imageversion.FieldDeletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ImageVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageVersionUpsertOne) UpdateNewValues() *ImageVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imageversion.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImageVersionUpsertOne) Ignore() *ImageVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageVersionUpsertOne) DoNothing() *ImageVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageVersionCreate.OnConflict
// documentation for more info.
func (u *ImageVersionUpsertOne) Update(set func(*ImageVersionUpsert)) *ImageVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetProjectID sets the "project_id" field.
func (u *ImageVersionUpsertOne) SetProjectID(v int64) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateProjectID() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateProjectID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ImageVersionUpsertOne) SetUserID(v int64) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateUserID() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateUserID()
	})
}

// SetParentVersionID sets the "parent_version_id" field.
func (u *ImageVersionUpsertOne) SetParentVersionID(v int64) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetParentVersionID(v)
	})
}

// AddParentVersionID adds v to the "parent_version_id" field.
func (u *ImageVersionUpsertOne) AddParentVersionID(v int64) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.AddParentVersionID(v)
	})
}

// UpdateParentVersionID sets the "parent_version_id" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateParentVersionID() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateParentVersionID()
	})
}

// ClearParentVersionID clears the value of the "parent_version_id" field.
func (u *ImageVersionUpsertOne) ClearParentVersionID() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearParentVersionID()
	})
}

// SetSourceVersionID sets the "source_version_id" field.
func (u *ImageVersionUpsertOne) SetSourceVersionID(v int64) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetSourceVersionID(v)
	})
}

// AddSourceVersionID adds v to the "source_version_id" field.
func (u *ImageVersionUpsertOne) AddSourceVersionID(v int64) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.AddSourceVersionID(v)
	})
}

// UpdateSourceVersionID sets the "source_version_id" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateSourceVersionID() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateSourceVersionID()
	})
}

// ClearSourceVersionID clears the value of the "source_version_id" field.
func (u *ImageVersionUpsertOne) ClearSourceVersionID() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearSourceVersionID()
	})
}

// SetMode sets the "mode" field.
func (u *ImageVersionUpsertOne) SetMode(v string) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateMode() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateMode()
	})
}

// SetPrompt sets the "prompt" field.
func (u *ImageVersionUpsertOne) SetPrompt(v string) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdatePrompt() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdatePrompt()
	})
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (u *ImageVersionUpsertOne) SetRevisedPrompt(v string) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetRevisedPrompt(v)
	})
}

// UpdateRevisedPrompt sets the "revised_prompt" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateRevisedPrompt() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateRevisedPrompt()
	})
}

// ClearRevisedPrompt clears the value of the "revised_prompt" field.
func (u *ImageVersionUpsertOne) ClearRevisedPrompt() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearRevisedPrompt()
	})
}

// SetModel sets the "model" field.
func (u *ImageVersionUpsertOne) SetModel(v string) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateModel() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateModel()
	})
}

// SetSize sets the "size" field.
func (u *ImageVersionUpsertOne) SetSize(v string) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateSize() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateSize()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *ImageVersionUpsertOne) SetMimeType(v string) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateMimeType() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateMimeType()
	})
}

// SetFilePath sets the "file_path" field.
func (u *ImageVersionUpsertOne) SetFilePath(v string) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetFilePath(v)
	})
}

// UpdateFilePath sets the "file_path" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateFilePath() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateFilePath()
	})
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (u *ImageVersionUpsertOne) SetFileSizeBytes(v int64) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetFileSizeBytes(v)
	})
}

// AddFileSizeBytes adds v to the "file_size_bytes" field.
func (u *ImageVersionUpsertOne) AddFileSizeBytes(v int64) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.AddFileSizeBytes(v)
	})
}

// UpdateFileSizeBytes sets the "file_size_bytes" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateFileSizeBytes() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateFileSizeBytes()
	})
}

// SetSha256 sets the "sha256" field.
func (u *ImageVersionUpsertOne) SetSha256(v string) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateSha256() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateSha256()
	})
}

// SetWidth sets the "width" field.
func (u *ImageVersionUpsertOne) SetWidth(v int) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *ImageVersionUpsertOne) AddWidth(v int) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateWidth() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateWidth()
	})
}

// SetHeight sets the "height" field.
func (u *ImageVersionUpsertOne) SetHeight(v int) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *ImageVersionUpsertOne) AddHeight(v int) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateHeight() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateHeight()
	})
}

// SetMaskFilePath sets the "mask_file_path" field.
func (u *ImageVersionUpsertOne) SetMaskFilePath(v string) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetMaskFilePath(v)
	})
}

// UpdateMaskFilePath sets the "mask_file_path" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateMaskFilePath() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateMaskFilePath()
	})
}

// ClearMaskFilePath clears the value of the "mask_file_path" field.
func (u *ImageVersionUpsertOne) ClearMaskFilePath() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearMaskFilePath()
	})
}

// SetMaskMimeType sets the "mask_mime_type" field.
func (u *ImageVersionUpsertOne) SetMaskMimeType(v string) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetMaskMimeType(v)
	})
}

// UpdateMaskMimeType sets the "mask_mime_type" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateMaskMimeType() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateMaskMimeType()
	})
}

// ClearMaskMimeType clears the value of the "mask_mime_type" field.
func (u *ImageVersionUpsertOne) ClearMaskMimeType() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearMaskMimeType()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ImageVersionUpsertOne) SetAPIKeyID(v int64) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *ImageVersionUpsertOne) AddAPIKeyID(v int64) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateAPIKeyID() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *ImageVersionUpsertOne) ClearAPIKeyID() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *ImageVersionUpsertOne) SetUsageLogID(v int64) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *ImageVersionUpsertOne) AddUsageLogID(v int64) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateUsageLogID() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *ImageVersionUpsertOne) ClearUsageLogID() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearUsageLogID()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ImageVersionUpsertOne) SetDeletedAt(v time.Time) *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ImageVersionUpsertOne) UpdateDeletedAt() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ImageVersionUpsertOne) ClearDeletedAt() *ImageVersionUpsertOne {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *ImageVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImageVersionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImageVersionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImageVersionCreateBulk is the builder for creating many ImageVersion entities in bulk.
type ImageVersionCreateBulk struct {
	config
	err      error
	builders []*ImageVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the ImageVersion entities in the database.
func (_c *ImageVersionCreateBulk) Save(ctx context.Context) ([]*ImageVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImageVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImageVersionCreateBulk) SaveX(ctx context.Context) []*ImageVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageVersionUpsert) {
//			SetProjectID(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImageVersionUpsertBulk {
	_c.conflict = opts
	return &ImageVersionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageVersionCreateBulk) OnConflictColumns(columns ...string) *ImageVersionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageVersionUpsertBulk{
		create: _c,
	}
}

// ImageVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of ImageVersion nodes.
type ImageVersionUpsertBulk struct {
	create *ImageVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ImageVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageVersionUpsertBulk) UpdateNewValues() *ImageVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imageversion.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImageVersionUpsertBulk) Ignore() *ImageVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageVersionUpsertBulk) DoNothing() *ImageVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageVersionCreateBulk.OnConflict
// documentation for more info.
func (u *ImageVersionUpsertBulk) Update(set func(*ImageVersionUpsert)) *ImageVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetProjectID sets the "project_id" field.
func (u *ImageVersionUpsertBulk) SetProjectID(v int64) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateProjectID() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateProjectID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ImageVersionUpsertBulk) SetUserID(v int64) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateUserID() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateUserID()
	})
}

// SetParentVersionID sets the "parent_version_id" field.
func (u *ImageVersionUpsertBulk) SetParentVersionID(v int64) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetParentVersionID(v)
	})
}

// AddParentVersionID adds v to the "parent_version_id" field.
func (u *ImageVersionUpsertBulk) AddParentVersionID(v int64) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.AddParentVersionID(v)
	})
}

// UpdateParentVersionID sets the "parent_version_id" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateParentVersionID() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateParentVersionID()
	})
}

// ClearParentVersionID clears the value of the "parent_version_id" field.
func (u *ImageVersionUpsertBulk) ClearParentVersionID() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearParentVersionID()
	})
}

// SetSourceVersionID sets the "source_version_id" field.
func (u *ImageVersionUpsertBulk) SetSourceVersionID(v int64) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetSourceVersionID(v)
	})
}

// AddSourceVersionID adds v to the "source_version_id" field.
func (u *ImageVersionUpsertBulk) AddSourceVersionID(v int64) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.AddSourceVersionID(v)
	})
}

// UpdateSourceVersionID sets the "source_version_id" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateSourceVersionID() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateSourceVersionID()
	})
}

// ClearSourceVersionID clears the value of the "source_version_id" field.
func (u *ImageVersionUpsertBulk) ClearSourceVersionID() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearSourceVersionID()
	})
}

// SetMode sets the "mode" field.
func (u *ImageVersionUpsertBulk) SetMode(v string) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateMode() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateMode()
	})
}

// SetPrompt sets the "prompt" field.
func (u *ImageVersionUpsertBulk) SetPrompt(v string) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdatePrompt() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdatePrompt()
	})
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (u *ImageVersionUpsertBulk) SetRevisedPrompt(v string) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetRevisedPrompt(v)
	})
}

// UpdateRevisedPrompt sets the "revised_prompt" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateRevisedPrompt() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateRevisedPrompt()
	})
}

// ClearRevisedPrompt clears the value of the "revised_prompt" field.
func (u *ImageVersionUpsertBulk) ClearRevisedPrompt() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearRevisedPrompt()
	})
}

// SetModel sets the "model" field.
func (u *ImageVersionUpsertBulk) SetModel(v string) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateModel() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateModel()
	})
}

// SetSize sets the "size" field.
func (u *ImageVersionUpsertBulk) SetSize(v string) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetSize(v)
	})
}

// UpdateSize sets the "size" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateSize() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateSize()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *ImageVersionUpsertBulk) SetMimeType(v string) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateMimeType() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateMimeType()
	})
}

// SetFilePath sets the "file_path" field.
func (u *ImageVersionUpsertBulk) SetFilePath(v string) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetFilePath(v)
	})
}

// UpdateFilePath sets the "file_path" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateFilePath() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateFilePath()
	})
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (u *ImageVersionUpsertBulk) SetFileSizeBytes(v int64) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetFileSizeBytes(v)
	})
}

// AddFileSizeBytes adds v to the "file_size_bytes" field.
func (u *ImageVersionUpsertBulk) AddFileSizeBytes(v int64) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.AddFileSizeBytes(v)
	})
}

// UpdateFileSizeBytes sets the "file_size_bytes" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateFileSizeBytes() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateFileSizeBytes()
	})
}

// SetSha256 sets the "sha256" field.
func (u *ImageVersionUpsertBulk) SetSha256(v string) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetSha256(v)
	})
}

// UpdateSha256 sets the "sha256" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateSha256() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateSha256()
	})
}

// SetWidth sets the "width" field.
func (u *ImageVersionUpsertBulk) SetWidth(v int) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *ImageVersionUpsertBulk) AddWidth(v int) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateWidth() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateWidth()
	})
}

// SetHeight sets the "height" field.
func (u *ImageVersionUpsertBulk) SetHeight(v int) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *ImageVersionUpsertBulk) AddHeight(v int) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateHeight() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateHeight()
	})
}

// SetMaskFilePath sets the "mask_file_path" field.
func (u *ImageVersionUpsertBulk) SetMaskFilePath(v string) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetMaskFilePath(v)
	})
}

// UpdateMaskFilePath sets the "mask_file_path" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateMaskFilePath() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateMaskFilePath()
	})
}

// ClearMaskFilePath clears the value of the "mask_file_path" field.
func (u *ImageVersionUpsertBulk) ClearMaskFilePath() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearMaskFilePath()
	})
}

// SetMaskMimeType sets the "mask_mime_type" field.
func (u *ImageVersionUpsertBulk) SetMaskMimeType(v string) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetMaskMimeType(v)
	})
}

// UpdateMaskMimeType sets the "mask_mime_type" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateMaskMimeType() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateMaskMimeType()
	})
}

// ClearMaskMimeType clears the value of the "mask_mime_type" field.
func (u *ImageVersionUpsertBulk) ClearMaskMimeType() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearMaskMimeType()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ImageVersionUpsertBulk) SetAPIKeyID(v int64) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *ImageVersionUpsertBulk) AddAPIKeyID(v int64) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateAPIKeyID() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *ImageVersionUpsertBulk) ClearAPIKeyID() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *ImageVersionUpsertBulk) SetUsageLogID(v int64) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetUsageLogID(v)
	})
}

// AddUsageLogID adds v to the "usage_log_id" field.
func (u *ImageVersionUpsertBulk) AddUsageLogID(v int64) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.AddUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateUsageLogID() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateUsageLogID()
	})
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (u *ImageVersionUpsertBulk) ClearUsageLogID() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearUsageLogID()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ImageVersionUpsertBulk) SetDeletedAt(v time.Time) *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ImageVersionUpsertBulk) UpdateDeletedAt() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ImageVersionUpsertBulk) ClearDeletedAt() *ImageVersionUpsertBulk {
	return u.Update(func(s *ImageVersionUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *ImageVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImageVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
