// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/imageproject"
	"github.com/Wei-Shaw/sub2api/ent/imageversion"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ImageVersion is the model entity for the ImageVersion schema.
type ImageVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID int64 `json:"project_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ParentVersionID holds the value of the "parent_version_id" field.
	ParentVersionID *int64 `json:"parent_version_id,omitempty"`
	// SourceVersionID holds the value of the "source_version_id" field.
	SourceVersionID *int64 `json:"source_version_id,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode string `json:"mode,omitempty"`
	// Prompt holds the value of the "prompt" field.
	Prompt string `json:"prompt,omitempty"`
	// RevisedPrompt holds the value of the "revised_prompt" field.
	RevisedPrompt *string `json:"revised_prompt,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Size holds the value of the "size" field.
	Size string `json:"size,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType string `json:"mime_type,omitempty"`
	// FilePath holds the value of the "file_path" field.
	FilePath string `json:"file_path,omitempty"`
	// FileSizeBytes holds the value of the "file_size_bytes" field.
	FileSizeBytes int64 `json:"file_size_bytes,omitempty"`
	// Sha256 holds the value of the "sha256" field.
	Sha256 string `json:"sha256,omitempty"`
	// Width holds the value of the "width" field.
	Width int `json:"width,omitempty"`
	// Height holds the value of the "height" field.
	Height int `json:"height,omitempty"`
	// MaskFilePath holds the value of the "mask_file_path" field.
	MaskFilePath *string `json:"mask_file_path,omitempty"`
	// MaskMimeType holds the value of the "mask_mime_type" field.
	MaskMimeType *string `json:"mask_mime_type,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID *int64 `json:"usage_log_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ImageVersionQuery when eager-loading is set.
	Edges        ImageVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ImageVersionEdges holds the relations/edges for other nodes in the graph.
type ImageVersionEdges struct {
	// Project holds the value of the project edge.
	Project *ImageProject `json:"project,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImageVersionEdges) ProjectOrErr() (*ImageProject, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: imageproject.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImageVersionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImageVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imageversion.FieldID, imageversion.FieldProjectID, imageversion.FieldUserID, imageversion.FieldParentVersionID, imageversion.FieldSourceVersionID, imageversion.FieldFileSizeBytes, imageversion.FieldWidth, imageversion.FieldHeight, imageversion.FieldAPIKeyID, imageversion.FieldUsageLogID:
			values[i] = new(sql.NullInt64)
		case imageversion.FieldMode, imageversion.FieldPrompt, imageversion.FieldRevisedPrompt, imageversion.FieldModel, imageversion.FieldSize, imageversion.FieldMimeType, imageversion.FieldFilePath, imageversion.FieldSha256, imageversion.FieldMaskFilePath, imageversion.FieldMaskMimeType:
			values[i] = new(sql.NullString)
		case imageversion.FieldCreatedAt, imageversion.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImageVersion fields.
func (_m *ImageVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imageversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case imageversion.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = value.Int64
			}
		case imageversion.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case imageversion.FieldParentVersionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_version_id", values[i])
			} else if value.Valid {
				_m.ParentVersionID = new(int64)
				*_m.ParentVersionID = value.Int64
			}
		case imageversion.FieldSourceVersionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_version_id", values[i])
			} else if value.Valid {
				_m.SourceVersionID = new(int64)
				*_m.SourceVersionID = value.Int64
			}
		case imageversion.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = value.String
			}
		case imageversion.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case imageversion.FieldRevisedPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revised_prompt", values[i])
			} else if value.Valid {
				_m.RevisedPrompt = new(string)
				*_m.RevisedPrompt = value.String
			}
		case imageversion.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case imageversion.FieldSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = value.String
			}
		case imageversion.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = value.String
			}
		case imageversion.FieldFilePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_path", values[i])
			} else if value.Valid {
				_m.FilePath = value.String
			}
		case imageversion.FieldFileSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size_bytes", values[i])
			} else if value.Valid {
				_m.FileSizeBytes = value.Int64
			}
		case imageversion.FieldSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sha256", values[i])
			} else if value.Valid {
				_m.Sha256 = value.String
			}
		case imageversion.FieldWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = int(value.Int64)
			}
		case imageversion.FieldHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = int(value.Int64)
			}
		case imageversion.FieldMaskFilePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mask_file_path", values[i])
			} else if value.Valid {
				_m.MaskFilePath = new(string)
				*_m.MaskFilePath = value.String
			}
		case imageversion.FieldMaskMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mask_mime_type", values[i])
			} else if value.Valid {
				_m.MaskMimeType = new(string)
				*_m.MaskMimeType = value.String
			}
		case imageversion.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case imageversion.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = new(int64)
				*_m.UsageLogID = value.Int64
			}
		case imageversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case imageversion.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImageVersion.
// This includes values selected through modifiers, order, etc.
func (_m *ImageVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the ImageVersion entity.
func (_m *ImageVersion) QueryProject() *ImageProjectQuery {
	return NewImageVersionClient(_m.config).QueryProject(_m)
}

// QueryUser queries the "user" edge of the ImageVersion entity.
func (_m *ImageVersion) QueryUser() *UserQuery {
	return NewImageVersionClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ImageVersion.
// Note that you need to call ImageVersion.Unwrap() before calling this method if this ImageVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImageVersion) Update() *ImageVersionUpdateOne {
	return NewImageVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImageVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImageVersion) Unwrap() *ImageVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImageVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImageVersion) String() string {
	var builder strings.Builder
	builder.WriteString("ImageVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.ParentVersionID; v != nil {
		builder.WriteString("parent_version_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SourceVersionID; v != nil {
		builder.WriteString("source_version_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(_m.Mode)
	builder.WriteString(", ")
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	if v := _m.RevisedPrompt; v != nil {
		builder.WriteString("revised_prompt=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(_m.Size)
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(_m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("file_path=")
	builder.WriteString(_m.FilePath)
	builder.WriteString(", ")
	builder.WriteString("file_size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileSizeBytes))
	builder.WriteString(", ")
	builder.WriteString("sha256=")
	builder.WriteString(_m.Sha256)
	builder.WriteString(", ")
	builder.WriteString("width=")
	builder.WriteString(fmt.Sprintf("%v", _m.Width))
	builder.WriteString(", ")
	builder.WriteString("height=")
	builder.WriteString(fmt.Sprintf("%v", _m.Height))
	builder.WriteString(", ")
	if v := _m.MaskFilePath; v != nil {
		builder.WriteString("mask_file_path=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.MaskMimeType; v != nil {
		builder.WriteString("mask_mime_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UsageLogID; v != nil {
		builder.WriteString("usage_log_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ImageVersions is a parsable slice of ImageVersion.
type ImageVersions []*ImageVersion
