// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imageproject"
	"github.com/Wei-Shaw/sub2api/ent/imageversion"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ImageVersionUpdate is the builder for updating ImageVersion entities.
type ImageVersionUpdate struct {
	config
	hooks    []Hook
	mutation *ImageVersionMutation
}

// Where appends a list predicates to the ImageVersionUpdate builder.
func (_u *ImageVersionUpdate) Where(ps ...predicate.ImageVersion) *ImageVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ImageVersionUpdate) SetProjectID(v int64) *ImageVersionUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableProjectID(v *int64) *ImageVersionUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ImageVersionUpdate) SetUserID(v int64) *ImageVersionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableUserID(v *int64) *ImageVersionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetParentVersionID sets the "parent_version_id" field.
func (_u *ImageVersionUpdate) SetParentVersionID(v int64) *ImageVersionUpdate {
	_u.mutation.ResetParentVersionID()
	_u.mutation.SetParentVersionID(v)
	return _u
}

// SetNillableParentVersionID sets the "parent_version_id" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableParentVersionID(v *int64) *ImageVersionUpdate {
	if v != nil {
		_u.SetParentVersionID(*v)
	}
	return _u
}

// AddParentVersionID adds value to the "parent_version_id" field.
func (_u *ImageVersionUpdate) AddParentVersionID(v int64) *ImageVersionUpdate {
	_u.mutation.AddParentVersionID(v)
	return _u
}

// ClearParentVersionID clears the value of the "parent_version_id" field.
func (_u *ImageVersionUpdate) ClearParentVersionID() *ImageVersionUpdate {
	_u.mutation.ClearParentVersionID()
	return _u
}

// SetSourceVersionID sets the "source_version_id" field.
func (_u *ImageVersionUpdate) SetSourceVersionID(v int64) *ImageVersionUpdate {
	_u.mutation.ResetSourceVersionID()
	_u.mutation.SetSourceVersionID(v)
	return _u
}

// SetNillableSourceVersionID sets the "source_version_id" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableSourceVersionID(v *int64) *ImageVersionUpdate {
	if v != nil {
		_u.SetSourceVersionID(*v)
	}
	return _u
}

// AddSourceVersionID adds value to the "source_version_id" field.
func (_u *ImageVersionUpdate) AddSourceVersionID(v int64) *ImageVersionUpdate {
	_u.mutation.AddSourceVersionID(v)
	return _u
}

// ClearSourceVersionID clears the value of the "source_version_id" field.
func (_u *ImageVersionUpdate) ClearSourceVersionID() *ImageVersionUpdate {
	_u.mutation.ClearSourceVersionID()
	return _u
}

// SetMode sets the "mode" field.
func (_u *ImageVersionUpdate) SetMode(v string) *ImageVersionUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableMode(v *string) *ImageVersionUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *ImageVersionUpdate) SetPrompt(v string) *ImageVersionUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillablePrompt(v *string) *ImageVersionUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (_u *ImageVersionUpdate) SetRevisedPrompt(v string) *ImageVersionUpdate {
	_u.mutation.SetRevisedPrompt(v)
	return _u
}

// SetNillableRevisedPrompt sets the "revised_prompt" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableRevisedPrompt(v *string) *ImageVersionUpdate {
	if v != nil {
		_u.SetRevisedPrompt(*v)
	}
	return _u
}

// ClearRevisedPrompt clears the value of the "revised_prompt" field.
func (_u *ImageVersionUpdate) ClearRevisedPrompt() *ImageVersionUpdate {
	_u.mutation.ClearRevisedPrompt()
	return _u
}

// SetModel sets the "model" field.
func (_u *ImageVersionUpdate) SetModel(v string) *ImageVersionUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableModel(v *string) *ImageVersionUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *ImageVersionUpdate) SetSize(v string) *ImageVersionUpdate {
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableSize(v *string) *ImageVersionUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ImageVersionUpdate) SetMimeType(v string) *ImageVersionUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableMimeType(v *string) *ImageVersionUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *ImageVersionUpdate) SetFilePath(v string) *ImageVersionUpdate {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableFilePath(v *string) *ImageVersionUpdate {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (_u *ImageVersionUpdate) SetFileSizeBytes(v int64) *ImageVersionUpdate {
	_u.mutation.ResetFileSizeBytes()
	_u.mutation.SetFileSizeBytes(v)
	return _u
}

// SetNillableFileSizeBytes sets the "file_size_bytes" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableFileSizeBytes(v *int64) *ImageVersionUpdate {
	if v != nil {
		_u.SetFileSizeBytes(*v)
	}
	return _u
}

// AddFileSizeBytes adds value to the "file_size_bytes" field.
func (_u *ImageVersionUpdate) AddFileSizeBytes(v int64) *ImageVersionUpdate {
	_u.mutation.AddFileSizeBytes(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *ImageVersionUpdate) SetSha256(v string) *ImageVersionUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableSha256(v *string) *ImageVersionUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *ImageVersionUpdate) SetWidth(v int) *ImageVersionUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableWidth(v *int) *ImageVersionUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ImageVersionUpdate) AddWidth(v int) *ImageVersionUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *ImageVersionUpdate) SetHeight(v int) *ImageVersionUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableHeight(v *int) *ImageVersionUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ImageVersionUpdate) AddHeight(v int) *ImageVersionUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// SetMaskFilePath sets the "mask_file_path" field.
func (_u *ImageVersionUpdate) SetMaskFilePath(v string) *ImageVersionUpdate {
	_u.mutation.SetMaskFilePath(v)
	return _u
}

// SetNillableMaskFilePath sets the "mask_file_path" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableMaskFilePath(v *string) *ImageVersionUpdate {
	if v != nil {
		_u.SetMaskFilePath(*v)
	}
	return _u
}

// ClearMaskFilePath clears the value of the "mask_file_path" field.
func (_u *ImageVersionUpdate) ClearMaskFilePath() *ImageVersionUpdate {
	_u.mutation.ClearMaskFilePath()
	return _u
}

// SetMaskMimeType sets the "mask_mime_type" field.
func (_u *ImageVersionUpdate) SetMaskMimeType(v string) *ImageVersionUpdate {
	_u.mutation.SetMaskMimeType(v)
	return _u
}

// SetNillableMaskMimeType sets the "mask_mime_type" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableMaskMimeType(v *string) *ImageVersionUpdate {
	if v != nil {
		_u.SetMaskMimeType(*v)
	}
	return _u
}

// ClearMaskMimeType clears the value of the "mask_mime_type" field.
func (_u *ImageVersionUpdate) ClearMaskMimeType() *ImageVersionUpdate {
	_u.mutation.ClearMaskMimeType()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ImageVersionUpdate) SetAPIKeyID(v int64) *ImageVersionUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableAPIKeyID(v *int64) *ImageVersionUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *ImageVersionUpdate) AddAPIKeyID(v int64) *ImageVersionUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *ImageVersionUpdate) ClearAPIKeyID() *ImageVersionUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *ImageVersionUpdate) SetUsageLogID(v int64) *ImageVersionUpdate {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableUsageLogID(v *int64) *ImageVersionUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *ImageVersionUpdate) AddUsageLogID(v int64) *ImageVersionUpdate {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *ImageVersionUpdate) ClearUsageLogID() *ImageVersionUpdate {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ImageVersionUpdate) SetDeletedAt(v time.Time) *ImageVersionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ImageVersionUpdate) SetNillableDeletedAt(v *time.Time) *ImageVersionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ImageVersionUpdate) ClearDeletedAt() *ImageVersionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetProject sets the "project" edge to the ImageProject entity.
func (_u *ImageVersionUpdate) SetProject(v *ImageProject) *ImageVersionUpdate {
	return _u.SetProjectID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ImageVersionUpdate) SetUser(v *User) *ImageVersionUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ImageVersionMutation object of the builder.
func (_u *ImageVersionUpdate) Mutation() *ImageVersionMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the ImageProject entity.
func (_u *ImageVersionUpdate) ClearProject() *ImageVersionUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ImageVersionUpdate) ClearUser() *ImageVersionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageVersionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageVersionUpdate) check() error {
	if v, ok := _u.mutation.Mode(); ok {
		if err := imageversion.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := imageversion.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Size(); ok {
		if err := imageversion.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := imageversion.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FilePath(); ok {
		if err := imageversion.FilePathValidator(v); err != nil {
			return &ValidationError{Name: "file_path", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.file_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := imageversion.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaskMimeType(); ok {
		if err := imageversion.MaskMimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mask_mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.mask_mime_type": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageVersion.project"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageVersion.user"`)
	}
	return nil
}

func (_u *ImageVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imageversion.Table, imageversion.Columns, sqlgraph.NewFieldSpec(imageversion.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ParentVersionID(); ok {
		_spec.SetField(imageversion.FieldParentVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentVersionID(); ok {
		_spec.AddField(imageversion.FieldParentVersionID, field.TypeInt64, value)
	}
	if _u.mutation.ParentVersionIDCleared() {
		_spec.ClearField(imageversion.FieldParentVersionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceVersionID(); ok {
		_spec.SetField(imageversion.FieldSourceVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceVersionID(); ok {
		_spec.AddField(imageversion.FieldSourceVersionID, field.TypeInt64, value)
	}
	if _u.mutation.SourceVersionIDCleared() {
		_spec.ClearField(imageversion.FieldSourceVersionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(imageversion.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(imageversion.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.RevisedPrompt(); ok {
		_spec.SetField(imageversion.FieldRevisedPrompt, field.TypeString, value)
	}
	if _u.mutation.RevisedPromptCleared() {
		_spec.ClearField(imageversion.FieldRevisedPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(imageversion.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(imageversion.FieldSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(imageversion.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(imageversion.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSizeBytes(); ok {
		_spec.SetField(imageversion.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSizeBytes(); ok {
		_spec.AddField(imageversion.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(imageversion.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(imageversion.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(imageversion.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(imageversion.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(imageversion.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaskFilePath(); ok {
		_spec.SetField(imageversion.FieldMaskFilePath, field.TypeString, value)
	}
	if _u.mutation.MaskFilePathCleared() {
		_spec.ClearField(imageversion.FieldMaskFilePath, field.TypeString)
	}
	if value, ok := _u.mutation.MaskMimeType(); ok {
		_spec.SetField(imageversion.FieldMaskMimeType, field.TypeString, value)
	}
	if _u.mutation.MaskMimeTypeCleared() {
		_spec.ClearField(imageversion.FieldMaskMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(imageversion.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(imageversion.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(imageversion.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(imageversion.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(imageversion.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(imageversion.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(imageversion.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(imageversion.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imageversion.ProjectTable,
			Columns: []string{imageversion.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imageproject.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imageversion.ProjectTable,
			Columns: []string{imageversion.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imageproject.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imageversion.UserTable,
			Columns: []string{imageversion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imageversion.UserTable,
			Columns: []string{imageversion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imageversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageVersionUpdateOne is the builder for updating a single ImageVersion entity.
type ImageVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageVersionMutation
}

// SetProjectID sets the "project_id" field.
func (_u *ImageVersionUpdateOne) SetProjectID(v int64) *ImageVersionUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableProjectID(v *int64) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ImageVersionUpdateOne) SetUserID(v int64) *ImageVersionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableUserID(v *int64) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetParentVersionID sets the "parent_version_id" field.
func (_u *ImageVersionUpdateOne) SetParentVersionID(v int64) *ImageVersionUpdateOne {
	_u.mutation.ResetParentVersionID()
	_u.mutation.SetParentVersionID(v)
	return _u
}

// SetNillableParentVersionID sets the "parent_version_id" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableParentVersionID(v *int64) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetParentVersionID(*v)
	}
	return _u
}

// AddParentVersionID adds value to the "parent_version_id" field.
func (_u *ImageVersionUpdateOne) AddParentVersionID(v int64) *ImageVersionUpdateOne {
	_u.mutation.AddParentVersionID(v)
	return _u
}

// ClearParentVersionID clears the value of the "parent_version_id" field.
func (_u *ImageVersionUpdateOne) ClearParentVersionID() *ImageVersionUpdateOne {
	_u.mutation.ClearParentVersionID()
	return _u
}

// SetSourceVersionID sets the "source_version_id" field.
func (_u *ImageVersionUpdateOne) SetSourceVersionID(v int64) *ImageVersionUpdateOne {
	_u.mutation.ResetSourceVersionID()
	_u.mutation.SetSourceVersionID(v)
	return _u
}

// SetNillableSourceVersionID sets the "source_version_id" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableSourceVersionID(v *int64) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetSourceVersionID(*v)
	}
	return _u
}

// AddSourceVersionID adds value to the "source_version_id" field.
func (_u *ImageVersionUpdateOne) AddSourceVersionID(v int64) *ImageVersionUpdateOne {
	_u.mutation.AddSourceVersionID(v)
	return _u
}

// ClearSourceVersionID clears the value of the "source_version_id" field.
func (_u *ImageVersionUpdateOne) ClearSourceVersionID() *ImageVersionUpdateOne {
	_u.mutation.ClearSourceVersionID()
	return _u
}

// SetMode sets the "mode" field.
func (_u *ImageVersionUpdateOne) SetMode(v string) *ImageVersionUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableMode(v *string) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *ImageVersionUpdateOne) SetPrompt(v string) *ImageVersionUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillablePrompt(v *string) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (_u *ImageVersionUpdateOne) SetRevisedPrompt(v string) *ImageVersionUpdateOne {
	_u.mutation.SetRevisedPrompt(v)
	return _u
}

// SetNillableRevisedPrompt sets the "revised_prompt" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableRevisedPrompt(v *string) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetRevisedPrompt(*v)
	}
	return _u
}

// ClearRevisedPrompt clears the value of the "revised_prompt" field.
func (_u *ImageVersionUpdateOne) ClearRevisedPrompt() *ImageVersionUpdateOne {
	_u.mutation.ClearRevisedPrompt()
	return _u
}

// SetModel sets the "model" field.
func (_u *ImageVersionUpdateOne) SetModel(v string) *ImageVersionUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableModel(v *string) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *ImageVersionUpdateOne) SetSize(v string) *ImageVersionUpdateOne {
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableSize(v *string) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ImageVersionUpdateOne) SetMimeType(v string) *ImageVersionUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableMimeType(v *string) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *ImageVersionUpdateOne) SetFilePath(v string) *ImageVersionUpdateOne {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableFilePath(v *string) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetFileSizeBytes sets the "file_size_bytes" field.
func (_u *ImageVersionUpdateOne) SetFileSizeBytes(v int64) *ImageVersionUpdateOne {
	_u.mutation.ResetFileSizeBytes()
	_u.mutation.SetFileSizeBytes(v)
	return _u
}

// SetNillableFileSizeBytes sets the "file_size_bytes" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableFileSizeBytes(v *int64) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetFileSizeBytes(*v)
	}
	return _u
}

// AddFileSizeBytes adds value to the "file_size_bytes" field.
func (_u *ImageVersionUpdateOne) AddFileSizeBytes(v int64) *ImageVersionUpdateOne {
	_u.mutation.AddFileSizeBytes(v)
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *ImageVersionUpdateOne) SetSha256(v string) *ImageVersionUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableSha256(v *string) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *ImageVersionUpdateOne) SetWidth(v int) *ImageVersionUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableWidth(v *int) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ImageVersionUpdateOne) AddWidth(v int) *ImageVersionUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *ImageVersionUpdateOne) SetHeight(v int) *ImageVersionUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableHeight(v *int) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ImageVersionUpdateOne) AddHeight(v int) *ImageVersionUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// SetMaskFilePath sets the "mask_file_path" field.
func (_u *ImageVersionUpdateOne) SetMaskFilePath(v string) *ImageVersionUpdateOne {
	_u.mutation.SetMaskFilePath(v)
	return _u
}

// SetNillableMaskFilePath sets the "mask_file_path" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableMaskFilePath(v *string) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetMaskFilePath(*v)
	}
	return _u
}

// ClearMaskFilePath clears the value of the "mask_file_path" field.
func (_u *ImageVersionUpdateOne) ClearMaskFilePath() *ImageVersionUpdateOne {
	_u.mutation.ClearMaskFilePath()
	return _u
}

// SetMaskMimeType sets the "mask_mime_type" field.
func (_u *ImageVersionUpdateOne) SetMaskMimeType(v string) *ImageVersionUpdateOne {
	_u.mutation.SetMaskMimeType(v)
	return _u
}

// SetNillableMaskMimeType sets the "mask_mime_type" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableMaskMimeType(v *string) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetMaskMimeType(*v)
	}
	return _u
}

// ClearMaskMimeType clears the value of the "mask_mime_type" field.
func (_u *ImageVersionUpdateOne) ClearMaskMimeType() *ImageVersionUpdateOne {
	_u.mutation.ClearMaskMimeType()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ImageVersionUpdateOne) SetAPIKeyID(v int64) *ImageVersionUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableAPIKeyID(v *int64) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *ImageVersionUpdateOne) AddAPIKeyID(v int64) *ImageVersionUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *ImageVersionUpdateOne) ClearAPIKeyID() *ImageVersionUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *ImageVersionUpdateOne) SetUsageLogID(v int64) *ImageVersionUpdateOne {
	_u.mutation.ResetUsageLogID()
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableUsageLogID(v *int64) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// AddUsageLogID adds value to the "usage_log_id" field.
func (_u *ImageVersionUpdateOne) AddUsageLogID(v int64) *ImageVersionUpdateOne {
	_u.mutation.AddUsageLogID(v)
	return _u
}

// ClearUsageLogID clears the value of the "usage_log_id" field.
func (_u *ImageVersionUpdateOne) ClearUsageLogID() *ImageVersionUpdateOne {
	_u.mutation.ClearUsageLogID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ImageVersionUpdateOne) SetDeletedAt(v time.Time) *ImageVersionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ImageVersionUpdateOne) SetNillableDeletedAt(v *time.Time) *ImageVersionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ImageVersionUpdateOne) ClearDeletedAt() *ImageVersionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetProject sets the "project" edge to the ImageProject entity.
func (_u *ImageVersionUpdateOne) SetProject(v *ImageProject) *ImageVersionUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ImageVersionUpdateOne) SetUser(v *User) *ImageVersionUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ImageVersionMutation object of the builder.
func (_u *ImageVersionUpdateOne) Mutation() *ImageVersionMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the ImageProject entity.
func (_u *ImageVersionUpdateOne) ClearProject() *ImageVersionUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ImageVersionUpdateOne) ClearUser() *ImageVersionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ImageVersionUpdate builder.
func (_u *ImageVersionUpdateOne) Where(ps ...predicate.ImageVersion) *ImageVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageVersionUpdateOne) Select(field string, fields ...string) *ImageVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImageVersion entity.
func (_u *ImageVersionUpdateOne) Save(ctx context.Context) (*ImageVersion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageVersionUpdateOne) SaveX(ctx context.Context) *ImageVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageVersionUpdateOne) check() error {
	if v, ok := _u.mutation.Mode(); ok {
		if err := imageversion.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := imageversion.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Size(); ok {
		if err := imageversion.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := imageversion.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FilePath(); ok {
		if err := imageversion.FilePathValidator(v); err != nil {
			return &ValidationError{Name: "file_path", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.file_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sha256(); ok {
		if err := imageversion.Sha256Validator(v); err != nil {
			return &ValidationError{Name: "sha256", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaskMimeType(); ok {
		if err := imageversion.MaskMimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mask_mime_type", err: fmt.Errorf(`ent: validator failed for field "ImageVersion.mask_mime_type": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageVersion.project"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageVersion.user"`)
	}
	return nil
}

func (_u *ImageVersionUpdateOne) sqlSave(ctx context.Context) (_node *ImageVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imageversion.Table, imageversion.Columns, sqlgraph.NewFieldSpec(imageversion.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImageVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imageversion.FieldID)
		for _, f := range fields {
			if !imageversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imageversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ParentVersionID(); ok {
		_spec.SetField(imageversion.FieldParentVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentVersionID(); ok {
		_spec.AddField(imageversion.FieldParentVersionID, field.TypeInt64, value)
	}
	if _u.mutation.ParentVersionIDCleared() {
		_spec.ClearField(imageversion.FieldParentVersionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceVersionID(); ok {
		_spec.SetField(imageversion.FieldSourceVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSourceVersionID(); ok {
		_spec.AddField(imageversion.FieldSourceVersionID, field.TypeInt64, value)
	}
	if _u.mutation.SourceVersionIDCleared() {
		_spec.ClearField(imageversion.FieldSourceVersionID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(imageversion.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(imageversion.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.RevisedPrompt(); ok {
		_spec.SetField(imageversion.FieldRevisedPrompt, field.TypeString, value)
	}
	if _u.mutation.RevisedPromptCleared() {
		_spec.ClearField(imageversion.FieldRevisedPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(imageversion.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(imageversion.FieldSize, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(imageversion.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(imageversion.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSizeBytes(); ok {
		_spec.SetField(imageversion.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSizeBytes(); ok {
		_spec.AddField(imageversion.FieldFileSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(imageversion.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(imageversion.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(imageversion.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(imageversion.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(imageversion.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaskFilePath(); ok {
		_spec.SetField(imageversion.FieldMaskFilePath, field.TypeString, value)
	}
	if _u.mutation.MaskFilePathCleared() {
		_spec.ClearField(imageversion.FieldMaskFilePath, field.TypeString)
	}
	if value, ok := _u.mutation.MaskMimeType(); ok {
		_spec.SetField(imageversion.FieldMaskMimeType, field.TypeString, value)
	}
	if _u.mutation.MaskMimeTypeCleared() {
		_spec.ClearField(imageversion.FieldMaskMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(imageversion.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(imageversion.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(imageversion.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.UsageLogID(); ok {
		_spec.SetField(imageversion.FieldUsageLogID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUsageLogID(); ok {
		_spec.AddField(imageversion.FieldUsageLogID, field.TypeInt64, value)
	}
	if _u.mutation.UsageLogIDCleared() {
		_spec.ClearField(imageversion.FieldUsageLogID, field.TypeInt64)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(imageversion.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(imageversion.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imageversion.ProjectTable,
			Columns: []string{imageversion.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imageproject.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imageversion.ProjectTable,
			Columns: []string{imageversion.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imageproject.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imageversion.UserTable,
			Columns: []string{imageversion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imageversion.UserTable,
			Columns: []string{imageversion.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ImageVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imageversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
